pushd 0xf10e_radicale-formula; git remote add mdupont git@github.com:h4ck3rm1k3/radicale-formula.git; popd
pushd 666jfox777_saltstack-elasticsearch-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-elasticsearch-formula.git; popd
pushd 666jfox777_saltstack-erlang-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-erlang-formula.git; popd
pushd 666jfox777_saltstack-grafana-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-grafana-formula.git; popd
pushd 666jfox777_saltstack-graphite-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-graphite-formula.git; popd
pushd 666jfox777_saltstack-kibana-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-kibana-formula.git; popd
pushd 666jfox777_saltstack-logstash-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-logstash-formula.git; popd
pushd 666jfox777_saltstack-rabbitmq-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-rabbitmq-formula.git; popd
pushd 666jfox777_saltstack-sensu-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-sensu-formula.git; popd
pushd 666jfox777_saltstack-statsite-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-statsite-formula.git; popd
pushd 666jfox777_saltstack-writr-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-writr-formula.git; popd
pushd 666jfox777_vagrant-monitor-everything; git remote add mdupont git@github.com:h4ck3rm1k3/vagrant-monitor-everything.git; popd
pushd 7oku_open-vm-tools-formula; git remote add mdupont git@github.com:h4ck3rm1k3/open-vm-tools-formula.git; popd
pushd aboe76_docker_centos_salt; git remote add mdupont git@github.com:h4ck3rm1k3/docker_centos_salt.git; popd
pushd accumulo_mvn-formula; git remote add mdupont git@github.com:h4ck3rm1k3/mvn-formula.git; popd
pushd Adcade_buildbot-formula; git remote add mdupont git@github.com:h4ck3rm1k3/buildbot-formula.git; popd
pushd Adcade_logstash-formula; git remote add mdupont git@github.com:h4ck3rm1k3/logstash-formula.git; popd
pushd Adcade_oracle-java-formula; git remote add mdupont git@github.com:h4ck3rm1k3/oracle-java-formula.git; popd
pushd Adcade_pypicloud-formula; git remote add mdupont git@github.com:h4ck3rm1k3/pypicloud-formula.git; popd
pushd Adcade_redis-formula; git remote add mdupont git@github.com:h4ck3rm1k3/redis-formula.git; popd
pushd Adcade_snmp-formula; git remote add mdupont git@github.com:h4ck3rm1k3/snmp-formula.git; popd
pushd Adcade_statsd-formula; git remote add mdupont git@github.com:h4ck3rm1k3/statsd-formula.git; popd
pushd Adcade_thrift-formula; git remote add mdupont git@github.com:h4ck3rm1k3/thrift-formula.git; popd
pushd Adcade_vertx-formula; git remote add mdupont git@github.com:h4ck3rm1k3/vertx-formula.git; popd
pushd ahammond_salt_collectd; git remote add mdupont git@github.com:h4ck3rm1k3/salt_collectd.git; popd
pushd ahammond_salt_hosts; git remote add mdupont git@github.com:h4ck3rm1k3/salt_hosts.git; popd
pushd ahammond_salt_iptables; git remote add mdupont git@github.com:h4ck3rm1k3/salt_iptables.git; popd
pushd ahammond_salt_logstash; git remote add mdupont git@github.com:h4ck3rm1k3/salt_logstash.git; popd
pushd ahammond_salt_redis; git remote add mdupont git@github.com:h4ck3rm1k3/salt_redis.git; popd
pushd ahammond_salt_znc; git remote add mdupont git@github.com:h4ck3rm1k3/salt_znc.git; popd
pushd ahammond_salt_zookeeper; git remote add mdupont git@github.com:h4ck3rm1k3/salt_zookeeper.git; popd
pushd AislerHQ_couchdb-formula; git remote add mdupont git@github.com:h4ck3rm1k3/couchdb-formula.git; popd
pushd akoumjian_salt-django-example; git remote add mdupont git@github.com:h4ck3rm1k3/salt-django-example.git; popd
pushd akoumjian_salt-git-module; git remote add mdupont git@github.com:h4ck3rm1k3/salt-git-module.git; popd
pushd akoumjian_salty-vagrant; git remote add mdupont git@github.com:h4ck3rm1k3/salty-vagrant.git; popd
pushd akoumjian_shaker; git remote add mdupont git@github.com:h4ck3rm1k3/shaker.git; popd
pushd aletessier_salt-formulas; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formulas.git; popd
pushd alexjennings_example-formula; git remote add mdupont git@github.com:h4ck3rm1k3/example-formula.git; popd
pushd alexjennings_solr-formula; git remote add mdupont git@github.com:h4ck3rm1k3/solr-formula.git; popd
pushd alexjennings_zookeeper-formula; git remote add mdupont git@github.com:h4ck3rm1k3/zookeeper-formula.git; popd
pushd alex-leonhardt_sensu-formula; git remote add mdupont git@github.com:h4ck3rm1k3/sensu-formula.git; popd
pushd allanparsons_salt-supervisord; git remote add mdupont git@github.com:h4ck3rm1k3/salt-supervisord.git; popd
pushd asmaps_bepasty-formula; git remote add mdupont git@github.com:h4ck3rm1k3/bepasty-formula.git; popd
pushd azuwis_gerrit-formula; git remote add mdupont git@github.com:h4ck3rm1k3/gerrit-formula.git; popd
pushd bclermont_states; git remote add mdupont git@github.com:h4ck3rm1k3/states.git; popd
pushd bechtoldt_amavis-formula; git remote add mdupont git@github.com:h4ck3rm1k3/amavis-formula.git; popd
pushd bechtoldt_aptcacherng-formula; git remote add mdupont git@github.com:h4ck3rm1k3/aptcacherng-formula.git; popd
pushd bechtoldt_apt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/apt-formula.git; popd
pushd bechtoldt_bash-formula; git remote add mdupont git@github.com:h4ck3rm1k3/bash-formula.git; popd
pushd bechtoldt_binddns-formula; git remote add mdupont git@github.com:h4ck3rm1k3/binddns-formula.git; popd
pushd bechtoldt_clamav-formula; git remote add mdupont git@github.com:h4ck3rm1k3/clamav-formula.git; popd
pushd bechtoldt_crypto-formula; git remote add mdupont git@github.com:h4ck3rm1k3/crypto-formula.git; popd
pushd bechtoldt_dnsmasq-formula; git remote add mdupont git@github.com:h4ck3rm1k3/dnsmasq-formula.git; popd
pushd bechtoldt_dovecot-formula; git remote add mdupont git@github.com:h4ck3rm1k3/dovecot-formula.git; popd
pushd bechtoldt_ebtables-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ebtables-formula.git; popd
pushd bechtoldt_ferm-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ferm-formula.git; popd
pushd bechtoldt_file-formula; git remote add mdupont git@github.com:h4ck3rm1k3/file-formula.git; popd
pushd bechtoldt_foreman-formula; git remote add mdupont git@github.com:h4ck3rm1k3/foreman-formula.git; popd
pushd bechtoldt_git-formula; git remote add mdupont git@github.com:h4ck3rm1k3/git-formula.git; popd
pushd bechtoldt_gitlab-formula; git remote add mdupont git@github.com:h4ck3rm1k3/gitlab-formula.git; popd
pushd bechtoldt_grub-formula; git remote add mdupont git@github.com:h4ck3rm1k3/grub-formula.git; popd
pushd bechtoldt_httpd-formula; git remote add mdupont git@github.com:h4ck3rm1k3/httpd-formula.git; popd
pushd bechtoldt_ipa-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ipa-formula.git; popd
pushd bechtoldt_iscdhcp-formula; git remote add mdupont git@github.com:h4ck3rm1k3/iscdhcp-formula.git; popd
pushd bechtoldt_java-formula; git remote add mdupont git@github.com:h4ck3rm1k3/java-formula.git; popd
pushd bechtoldt_keepalived-formula; git remote add mdupont git@github.com:h4ck3rm1k3/keepalived-formula.git; popd
pushd bechtoldt_libvirt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/libvirt-formula.git; popd
pushd bechtoldt_linux-formula; git remote add mdupont git@github.com:h4ck3rm1k3/linux-formula.git; popd
pushd bechtoldt_liveconfig-formula; git remote add mdupont git@github.com:h4ck3rm1k3/liveconfig-formula.git; popd
pushd bechtoldt_mysql-formula; git remote add mdupont git@github.com:h4ck3rm1k3/mysql-formula.git; popd
pushd bechtoldt_network-formula; git remote add mdupont git@github.com:h4ck3rm1k3/network-formula.git; popd
pushd bechtoldt_nfs-formula; git remote add mdupont git@github.com:h4ck3rm1k3/nfs-formula.git; popd
pushd bechtoldt_nginx-formula; git remote add mdupont git@github.com:h4ck3rm1k3/nginx-formula.git; popd
pushd bechtoldt_omd-formula; git remote add mdupont git@github.com:h4ck3rm1k3/omd-formula.git; popd
pushd bechtoldt_opennebula-formula; git remote add mdupont git@github.com:h4ck3rm1k3/opennebula-formula.git; popd
pushd bechtoldt_openvswitch-formula; git remote add mdupont git@github.com:h4ck3rm1k3/openvswitch-formula.git; popd
pushd bechtoldt_php-formula; git remote add mdupont git@github.com:h4ck3rm1k3/php-formula.git; popd
pushd bechtoldt_postfix-formula; git remote add mdupont git@github.com:h4ck3rm1k3/postfix-formula.git; popd
pushd bechtoldt_postgresql-formula; git remote add mdupont git@github.com:h4ck3rm1k3/postgresql-formula.git; popd
pushd bechtoldt_redis-formula; git remote add mdupont git@github.com:h4ck3rm1k3/redis-formula.git; popd
pushd bechtoldt_repositorio-formula; git remote add mdupont git@github.com:h4ck3rm1k3/repositorio-formula.git; popd
pushd bechtoldt_rex-formula; git remote add mdupont git@github.com:h4ck3rm1k3/rex-formula.git; popd
pushd bechtoldt_salt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula.git; popd
pushd bechtoldt_saltstack-amavis-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-amavis-formula.git; popd
pushd bechtoldt_saltstack-aptcacherng-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-aptcacherng-formula.git; popd
pushd bechtoldt_saltstack-bash-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-bash-formula.git; popd
pushd bechtoldt_saltstack-binddns-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-binddns-formula.git; popd
pushd bechtoldt_saltstack-clamav-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-clamav-formula.git; popd
pushd bechtoldt_saltstack-cron-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-cron-formula.git; popd
pushd bechtoldt_saltstack-crypto-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-crypto-formula.git; popd
pushd bechtoldt_saltstack-dnsmasq-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-dnsmasq-formula.git; popd
pushd bechtoldt_saltstack-dovecot-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-dovecot-formula.git; popd
pushd bechtoldt_saltstack-duply-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-duply-formula.git; popd
pushd bechtoldt_saltstack-ebtables-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-ebtables-formula.git; popd
pushd bechtoldt_saltstack-elasticsearch-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-elasticsearch-formula.git; popd
pushd bechtoldt_saltstack-ferm-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-ferm-formula.git; popd
pushd bechtoldt_saltstack-file-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-file-formula.git; popd
pushd bechtoldt_saltstack-foreman-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-foreman-formula.git; popd
pushd bechtoldt_saltstack-git-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-git-formula.git; popd
pushd bechtoldt_saltstack-grub-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-grub-formula.git; popd
pushd bechtoldt_saltstack-httpd-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-httpd-formula.git; popd
pushd bechtoldt_saltstack-ipa-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-ipa-formula.git; popd
pushd bechtoldt_saltstack-java-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-java-formula.git; popd
pushd bechtoldt_saltstack-keepalived-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-keepalived-formula.git; popd
pushd bechtoldt_saltstack-libvirt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-libvirt-formula.git; popd
pushd bechtoldt_saltstack-liveconfig-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-liveconfig-formula.git; popd
pushd bechtoldt_saltstack-mongodb-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-mongodb-formula.git; popd
pushd bechtoldt_saltstack-myback-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-myback-formula.git; popd
pushd bechtoldt_saltstack-mysql-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-mysql-formula.git; popd
pushd bechtoldt_saltstack-network-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-network-formula.git; popd
pushd bechtoldt_saltstack-nfs-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-nfs-formula.git; popd
pushd bechtoldt_saltstack-nginx-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-nginx-formula.git; popd
pushd bechtoldt_saltstack-omd-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-omd-formula.git; popd
pushd bechtoldt_saltstack-opennebula-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-opennebula-formula.git; popd
pushd bechtoldt_saltstack-openvswitch-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-openvswitch-formula.git; popd
pushd bechtoldt_saltstack-pam-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-pam-formula.git; popd
pushd bechtoldt_saltstack-postfix-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-postfix-formula.git; popd
pushd bechtoldt_saltstack-postgresql-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-postgresql-formula.git; popd
pushd bechtoldt_saltstack-pulp-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-pulp-formula.git; popd
pushd bechtoldt_saltstack-repositorio-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-repositorio-formula.git; popd
pushd bechtoldt_saltstack-rex-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-rex-formula.git; popd
pushd bechtoldt_saltstack-rssh-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-rssh-formula.git; popd
pushd bechtoldt_saltstack-salt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-salt-formula.git; popd
pushd bechtoldt_saltstack-spamassassin-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-spamassassin-formula.git; popd
pushd bechtoldt_saltstack-squid-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-squid-formula.git; popd
pushd bechtoldt_saltstack-ssh-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-ssh-formula.git; popd
pushd bechtoldt_saltstack-sudo-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-sudo-formula.git; popd
pushd bechtoldt_saltstack-sysctl-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-sysctl-formula.git; popd
pushd bechtoldt_saltstack-sysvinit-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-sysvinit-formula.git; popd
pushd bechtoldt_saltstack-template-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-template-formula.git; popd
pushd bechtoldt_saltstack-tftp-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-tftp-formula.git; popd
pushd bechtoldt_saltstack-time-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-time-formula.git; popd
pushd bechtoldt_saltstack-tinc-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-tinc-formula.git; popd
pushd bechtoldt_saltstack-tools-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-tools-formula.git; popd
pushd bechtoldt_saltstack-users-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-users-formula.git; popd
pushd bechtoldt_saltstack-varnish-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-varnish-formula.git; popd
pushd bechtoldt_saltstack-vim-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-vim-formula.git; popd
pushd bechtoldt_saltstack-webapp-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-webapp-formula.git; popd
pushd bechtoldt_saltstack-yubikey-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-yubikey-formula.git; popd
pushd bechtoldt_saltstack-zsh-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-zsh-formula.git; popd
pushd bechtoldt_spamassassin-formula; git remote add mdupont git@github.com:h4ck3rm1k3/spamassassin-formula.git; popd
pushd bechtoldt_squid-formula; git remote add mdupont git@github.com:h4ck3rm1k3/squid-formula.git; popd
pushd bechtoldt_ssh-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ssh-formula.git; popd
pushd bechtoldt_ssl-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ssl-formula.git; popd
pushd bechtoldt_sudo-formula; git remote add mdupont git@github.com:h4ck3rm1k3/sudo-formula.git; popd
pushd bechtoldt_sysctl-formula; git remote add mdupont git@github.com:h4ck3rm1k3/sysctl-formula.git; popd
pushd bechtoldt_template-formula; git remote add mdupont git@github.com:h4ck3rm1k3/template-formula.git; popd
pushd bechtoldt_tftp-formula; git remote add mdupont git@github.com:h4ck3rm1k3/tftp-formula.git; popd
pushd bechtoldt_time-formula; git remote add mdupont git@github.com:h4ck3rm1k3/time-formula.git; popd
pushd bechtoldt_tools-formula; git remote add mdupont git@github.com:h4ck3rm1k3/tools-formula.git; popd
pushd bechtoldt_users-formula; git remote add mdupont git@github.com:h4ck3rm1k3/users-formula.git; popd
pushd bechtoldt_vim-formula; git remote add mdupont git@github.com:h4ck3rm1k3/vim-formula.git; popd
pushd bechtoldt_zsh-formula; git remote add mdupont git@github.com:h4ck3rm1k3/zsh-formula.git; popd
pushd blarghmatey_aws-formula; git remote add mdupont git@github.com:h4ck3rm1k3/aws-formula.git; popd
pushd blarghmatey_elasticsearch-formula; git remote add mdupont git@github.com:h4ck3rm1k3/elasticsearch-formula.git; popd
pushd blarghmatey_kibana-formula; git remote add mdupont git@github.com:h4ck3rm1k3/kibana-formula.git; popd
pushd blarghmatey_logstash-formula; git remote add mdupont git@github.com:h4ck3rm1k3/logstash-formula.git; popd
pushd blarghmatey_mongo-mms-formula; git remote add mdupont git@github.com:h4ck3rm1k3/mongo-mms-formula.git; popd
pushd blarghmatey_nginx-formula; git remote add mdupont git@github.com:h4ck3rm1k3/nginx-formula.git; popd
pushd blarghmatey_salt-formulas; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formulas.git; popd
pushd blarghmatey_saltstack-master; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-master.git; popd
pushd blarghmatey_uwsgi-formula; git remote add mdupont git@github.com:h4ck3rm1k3/uwsgi-formula.git; popd
pushd brandentimm_logstash-formula; git remote add mdupont git@github.com:h4ck3rm1k3/logstash-formula.git; popd
pushd brandentimm_logstash_forwarder-formula; git remote add mdupont git@github.com:h4ck3rm1k3/logstash_forwarder-formula.git; popd
pushd brandonhimpfen_ghost-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ghost-formula.git; popd
pushd brandonhimpfen_wordpress-formula; git remote add mdupont git@github.com:h4ck3rm1k3/wordpress-formula.git; popd
pushd brutasse_states; git remote add mdupont git@github.com:h4ck3rm1k3/states.git; popd
pushd Cantemo_python27-saltstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/python27-saltstack-formula.git; popd
pushd carlosperello_amavis-formula; git remote add mdupont git@github.com:h4ck3rm1k3/amavis-formula.git; popd
pushd carlosperello_newrelic-formula; git remote add mdupont git@github.com:h4ck3rm1k3/newrelic-formula.git; popd
pushd carlosperello_serverdensity-formula; git remote add mdupont git@github.com:h4ck3rm1k3/serverdensity-formula.git; popd
pushd chekolyn_cherokee-formula; git remote add mdupont git@github.com:h4ck3rm1k3/cherokee-formula.git; popd
pushd ckng_openjdk-formula; git remote add mdupont git@github.com:h4ck3rm1k3/openjdk-formula.git; popd
pushd clemensberndt_jboss-fuse-formula; git remote add mdupont git@github.com:h4ck3rm1k3/jboss-fuse-formula.git; popd
pushd clemensberndt_rundeck-formula; git remote add mdupont git@github.com:h4ck3rm1k3/rundeck-formula.git; popd
pushd clemensberndt_servicemix-formula; git remote add mdupont git@github.com:h4ck3rm1k3/servicemix-formula.git; popd
pushd cmeisinger_salt-starters; git remote add mdupont git@github.com:h4ck3rm1k3/salt-starters.git; popd
pushd ctrlaltlinux_salt-formulas; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formulas.git; popd
pushd Cyclohex_formulas; git remote add mdupont git@github.com:h4ck3rm1k3/formulas.git; popd
pushd daemonna_saltstack-jenkins; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-jenkins.git; popd
pushd dani4571_drupal; git remote add mdupont git@github.com:h4ck3rm1k3/drupal.git; popd
pushd dani4571_magento; git remote add mdupont git@github.com:h4ck3rm1k3/magento.git; popd
pushd dani4571_mysql; git remote add mdupont git@github.com:h4ck3rm1k3/mysql.git; popd
pushd danieljn_salt-states; git remote add mdupont git@github.com:h4ck3rm1k3/salt-states.git; popd
pushd DataDog_datadog-formula; git remote add mdupont git@github.com:h4ck3rm1k3/datadog-formula.git; popd
pushd davidkarlsen_subsonic-formula; git remote add mdupont git@github.com:h4ck3rm1k3/subsonic-formula.git; popd
pushd deuscapturus_saltstack-manageiq-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-manageiq-formula.git; popd
pushd diegows_accumulo-formula; git remote add mdupont git@github.com:h4ck3rm1k3/accumulo-formula.git; popd
pushd DigitalOcean-User-Projects_freepbx-saltstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/freepbx-saltstack-formula.git; popd
pushd djl_motd-formula; git remote add mdupont git@github.com:h4ck3rm1k3/motd-formula.git; popd
pushd djl_timezone-formula; git remote add mdupont git@github.com:h4ck3rm1k3/timezone-formula.git; popd
pushd dlax_ckan-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ckan-formula.git; popd
pushd dmyerscough_salt-formulas; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formulas.git; popd
pushd DockerNAS_nfs-yamlscript-formula; git remote add mdupont git@github.com:h4ck3rm1k3/nfs-yamlscript-formula.git; popd
pushd dockU_docker-formula; git remote add mdupont git@github.com:h4ck3rm1k3/docker-formula.git; popd
pushd dstritzel_salt-experiments; git remote add mdupont git@github.com:h4ck3rm1k3/salt-experiments.git; popd
pushd duk3luk3_nfs-user-formula; git remote add mdupont git@github.com:h4ck3rm1k3/nfs-user-formula.git; popd
pushd elastic-coders_saltstack-uwsgi-ng-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-uwsgi-ng-formula.git; popd
pushd elextro_mariadb-galera-salt-ubuntu-formula; git remote add mdupont git@github.com:h4ck3rm1k3/mariadb-galera-salt-ubuntu-formula.git; popd
pushd elvard_age-of-saltstack; git remote add mdupont git@github.com:h4ck3rm1k3/age-of-saltstack.git; popd
pushd Enrise_apache-formula; git remote add mdupont git@github.com:h4ck3rm1k3/apache-formula.git; popd
pushd Enrise_composer-formula; git remote add mdupont git@github.com:h4ck3rm1k3/composer-formula.git; popd
pushd Enrise_mariadb-formula; git remote add mdupont git@github.com:h4ck3rm1k3/mariadb-formula.git; popd
pushd Enrise_nginx-formula; git remote add mdupont git@github.com:h4ck3rm1k3/nginx-formula.git; popd
pushd Enrise_node-formula; git remote add mdupont git@github.com:h4ck3rm1k3/node-formula.git; popd
pushd Enrise_phpfpm-formula; git remote add mdupont git@github.com:h4ck3rm1k3/phpfpm-formula.git; popd
pushd EntropyWorks_salt-openstack; git remote add mdupont git@github.com:h4ck3rm1k3/salt-openstack.git; popd
pushd erzengel_node-formula; git remote add mdupont git@github.com:h4ck3rm1k3/node-formula.git; popd
pushd esacteksab_learning-salt; git remote add mdupont git@github.com:h4ck3rm1k3/learning-salt.git; popd
pushd esacteksab_salt-states; git remote add mdupont git@github.com:h4ck3rm1k3/salt-states.git; popd
pushd ExtremeSitting_hadoop-formula; git remote add mdupont git@github.com:h4ck3rm1k3/hadoop-formula.git; popd
pushd FEI-Lithicon_cobbler-formula; git remote add mdupont git@github.com:h4ck3rm1k3/cobbler-formula.git; popd
pushd FEI-Lithicon_common-packages-formula; git remote add mdupont git@github.com:h4ck3rm1k3/common-packages-formula.git; popd
pushd FEI-Lithicon_flexnet-server-formula; git remote add mdupont git@github.com:h4ck3rm1k3/flexnet-server-formula.git; popd
pushd FEI-Lithicon_observium-formula; git remote add mdupont git@github.com:h4ck3rm1k3/observium-formula.git; popd
pushd fessoga5_networkbsd-formula; git remote add mdupont git@github.com:h4ck3rm1k3/networkbsd-formula.git; popd
pushd fessoga5_saltstack-cron-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-cron-formula.git; popd
pushd fintanmm_alfresco-formula; git remote add mdupont git@github.com:h4ck3rm1k3/alfresco-formula.git; popd
pushd fintanmm_collectd-formula; git remote add mdupont git@github.com:h4ck3rm1k3/collectd-formula.git; popd
pushd fintanmm_eramba-formula; git remote add mdupont git@github.com:h4ck3rm1k3/eramba-formula.git; popd
pushd fintanmm_libreoffice-formula; git remote add mdupont git@github.com:h4ck3rm1k3/libreoffice-formula.git; popd
pushd fintanmm_proftpd-formula; git remote add mdupont git@github.com:h4ck3rm1k3/proftpd-formula.git; popd
pushd fintanmm_vmware-tools-formula; git remote add mdupont git@github.com:h4ck3rm1k3/vmware-tools-formula.git; popd
pushd fly_rsyslogd-formula; git remote add mdupont git@github.com:h4ck3rm1k3/rsyslogd-formula.git; popd
pushd glomium_django-project-formula; git remote add mdupont git@github.com:h4ck3rm1k3/django-project-formula.git; popd
pushd gravyboat_fail2ban-formula; git remote add mdupont git@github.com:h4ck3rm1k3/fail2ban-formula.git; popd
pushd grengojbo_python3-formula; git remote add mdupont git@github.com:h4ck3rm1k3/python3-formula.git; popd
pushd gspe_dropbox-formula; git remote add mdupont git@github.com:h4ck3rm1k3/dropbox-formula.git; popd
pushd gsyt_salt-autofs; git remote add mdupont git@github.com:h4ck3rm1k3/salt-autofs.git; popd
pushd gsyt_salt-bind9; git remote add mdupont git@github.com:h4ck3rm1k3/salt-bind9.git; popd
pushd gsyt_salt-byobu; git remote add mdupont git@github.com:h4ck3rm1k3/salt-byobu.git; popd
pushd gsyt_salt-dhcpd; git remote add mdupont git@github.com:h4ck3rm1k3/salt-dhcpd.git; popd
pushd gsyt_salt-foreman; git remote add mdupont git@github.com:h4ck3rm1k3/salt-foreman.git; popd
pushd gsyt_salt-galera; git remote add mdupont git@github.com:h4ck3rm1k3/salt-galera.git; popd
pushd gsyt_salt-git; git remote add mdupont git@github.com:h4ck3rm1k3/salt-git.git; popd
pushd gsyt_salt-nfs; git remote add mdupont git@github.com:h4ck3rm1k3/salt-nfs.git; popd
pushd gsyt_salt-nrpe; git remote add mdupont git@github.com:h4ck3rm1k3/salt-nrpe.git; popd
pushd gsyt_salt-ntp; git remote add mdupont git@github.com:h4ck3rm1k3/salt-ntp.git; popd
pushd gsyt_salt-pkgs; git remote add mdupont git@github.com:h4ck3rm1k3/salt-pkgs.git; popd
pushd gsyt_salt-vim; git remote add mdupont git@github.com:h4ck3rm1k3/salt-vim.git; popd
pushd gsyt_salt-vmwaretools; git remote add mdupont git@github.com:h4ck3rm1k3/salt-vmwaretools.git; popd
pushd gsyt_salt-yum; git remote add mdupont git@github.com:h4ck3rm1k3/salt-yum.git; popd
pushd gsyt_salt-zsh; git remote add mdupont git@github.com:h4ck3rm1k3/salt-zsh.git; popd
pushd hipikat_chippery-formula; git remote add mdupont git@github.com:h4ck3rm1k3/chippery-formula.git; popd
pushd hipikat_git-server-formula; git remote add mdupont git@github.com:h4ck3rm1k3/git-server-formula.git; popd
pushd hipikat_homeboy-formula; git remote add mdupont git@github.com:h4ck3rm1k3/homeboy-formula.git; popd
pushd hipikat_salt-formulas; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formulas.git; popd
pushd hipikat_saltlick-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltlick-formula.git; popd
pushd holmboe_django-saltapi; git remote add mdupont git@github.com:h4ck3rm1k3/django-saltapi.git; popd
pushd hotienvu_oracle-java7-salt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/oracle-java7-salt-formula.git; popd
pushd humankeyboard_salt-juno; git remote add mdupont git@github.com:h4ck3rm1k3/salt-juno.git; popd
pushd hvnsweeting_saltstates; git remote add mdupont git@github.com:h4ck3rm1k3/saltstates.git; popd
pushd iamseth_elasticsearch-formula; git remote add mdupont git@github.com:h4ck3rm1k3/elasticsearch-formula.git; popd
pushd iamseth_rundeck-formula; git remote add mdupont git@github.com:h4ck3rm1k3/rundeck-formula.git; popd
pushd iamseth_sphinx-formula; git remote add mdupont git@github.com:h4ck3rm1k3/sphinx-formula.git; popd
pushd ibrahim1211_apccache-sls; git remote add mdupont git@github.com:h4ck3rm1k3/apccache-sls.git; popd
pushd iluminite_reclass-tests; git remote add mdupont git@github.com:h4ck3rm1k3/reclass-tests.git; popd
pushd iluminite_salt-simple-stack; git remote add mdupont git@github.com:h4ck3rm1k3/salt-simple-stack.git; popd
pushd iluminite_vagrant-salt-example; git remote add mdupont git@github.com:h4ck3rm1k3/vagrant-salt-example.git; popd
pushd Inikup_subversion-formula; git remote add mdupont git@github.com:h4ck3rm1k3/subversion-formula.git; popd
pushd ipmb_hoodie-salt; git remote add mdupont git@github.com:h4ck3rm1k3/hoodie-salt.git; popd
pushd janusle_blog-env-formula; git remote add mdupont git@github.com:h4ck3rm1k3/blog-env-formula.git; popd
pushd janusle_Yan-devbox-formula; git remote add mdupont git@github.com:h4ck3rm1k3/Yan-devbox-formula.git; popd
pushd jarosser06_sysdig-formula; git remote add mdupont git@github.com:h4ck3rm1k3/sysdig-formula.git; popd
pushd jaypei_saltstack-formulas-workenv; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-formulas-workenv.git; popd
pushd jeffh_Seafood; git remote add mdupont git@github.com:h4ck3rm1k3/Seafood.git; popd
pushd jeffrey4l_horizon-salt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/horizon-salt-formula.git; popd
pushd jesusaurus_salt-formula-apt; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula-apt.git; popd
pushd jesusaurus_salt-formula-datadog; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula-datadog.git; popd
pushd jesusaurus_salt-formula-elasticsearch; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula-elasticsearch.git; popd
pushd jesusaurus_salt-formula-fail2ban; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula-fail2ban.git; popd
pushd jesusaurus_salt-formula-haproxy; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula-haproxy.git; popd
pushd jesusaurus_salt-formula-logstash; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula-logstash.git; popd
pushd jesusaurus_salt-formula-nginx; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula-nginx.git; popd
pushd jesusaurus_salt-formula-ntp; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula-ntp.git; popd
pushd jesusaurus_salt-formula-openvpn; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula-openvpn.git; popd
pushd jesusaurus_salt-formula-percona; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula-percona.git; popd
pushd jesusaurus_salt-formula-rabbitmq; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula-rabbitmq.git; popd
pushd jesusaurus_salt-formula-redis; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula-redis.git; popd
pushd jesusaurus_salt-formula-tinc; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula-tinc.git; popd
pushd jesusaurus_salt-formula-upstart; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula-upstart.git; popd
pushd jianingy_saltstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-formula.git; popd
pushd JoeHazzers_salt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula.git; popd
pushd JoeHazzers_salt-formula-cern; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula-cern.git; popd
pushd johnswanson_anaconda-formula; git remote add mdupont git@github.com:h4ck3rm1k3/anaconda-formula.git; popd
pushd johnswanson_jds-formula; git remote add mdupont git@github.com:h4ck3rm1k3/jds-formula.git; popd
pushd joshdover_albedolabs-salt-formulas; git remote add mdupont git@github.com:h4ck3rm1k3/albedolabs-salt-formulas.git; popd
pushd joshsmith2_salt-utils; git remote add mdupont git@github.com:h4ck3rm1k3/salt-utils.git; popd
pushd jxstanford_remi-formula; git remote add mdupont git@github.com:h4ck3rm1k3/remi-formula.git; popd
pushd kennydo_salt-btsync-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-btsync-formula.git; popd
pushd kennydo_salt-nginx-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-nginx-formula.git; popd
pushd kennydo_salt-transmission-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-transmission-formula.git; popd
pushd Kenshir0_apt-cacher-ng-formula; git remote add mdupont git@github.com:h4ck3rm1k3/apt-cacher-ng-formula.git; popd
pushd ketzacoatl_salt-aws-experiments; git remote add mdupont git@github.com:h4ck3rm1k3/salt-aws-experiments.git; popd
pushd kevinschoon_supervisor-formula; git remote add mdupont git@github.com:h4ck3rm1k3/supervisor-formula.git; popd
pushd kindleit_nagios-formula; git remote add mdupont git@github.com:h4ck3rm1k3/nagios-formula.git; popd
pushd kjoconnor_salt-contrib; git remote add mdupont git@github.com:h4ck3rm1k3/salt-contrib.git; popd
pushd KrisSaxton_salt-ldap; git remote add mdupont git@github.com:h4ck3rm1k3/salt-ldap.git; popd
pushd kshenk1_salt-formulas; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formulas.git; popd
pushd kvmate_kvmate-formula; git remote add mdupont git@github.com:h4ck3rm1k3/kvmate-formula.git; popd
pushd lblasc_ganeti-salt; git remote add mdupont git@github.com:h4ck3rm1k3/ganeti-salt.git; popd
pushd lemonlatte_mongodb-10gen; git remote add mdupont git@github.com:h4ck3rm1k3/mongodb-10gen.git; popd
pushd lemonlatte_openstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/openstack-formula.git; popd
pushd log0ymxm_salt-clojure; git remote add mdupont git@github.com:h4ck3rm1k3/salt-clojure.git; popd
pushd log0ymxm_salt-cuda; git remote add mdupont git@github.com:h4ck3rm1k3/salt-cuda.git; popd
pushd log0ymxm_salt-drake; git remote add mdupont git@github.com:h4ck3rm1k3/salt-drake.git; popd
pushd log0ymxm_salt-jvm; git remote add mdupont git@github.com:h4ck3rm1k3/salt-jvm.git; popd
pushd log0ymxm_salt-screen; git remote add mdupont git@github.com:h4ck3rm1k3/salt-screen.git; popd
pushd log0ymxm_salt-vowpal-wabbit; git remote add mdupont git@github.com:h4ck3rm1k3/salt-vowpal-wabbit.git; popd
pushd madflojo_salt-api-reactor-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-api-reactor-formula.git; popd
pushd MadRussian_apt-cacher-formula; git remote add mdupont git@github.com:h4ck3rm1k3/apt-cacher-formula.git; popd
pushd mafrosis_salt-formulae; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formulae.git; popd
pushd malept_gmusicprocurator-formula; git remote add mdupont git@github.com:h4ck3rm1k3/gmusicprocurator-formula.git; popd
pushd MarathonData_saltstack-formulas; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-formulas.git; popd
pushd markcwill_mark-formulas; git remote add mdupont git@github.com:h4ck3rm1k3/mark-formulas.git; popd
pushd markkimsal_saltstack-formula-mariadb; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-formula-mariadb.git; popd
pushd mathcamp_aws-formula; git remote add mdupont git@github.com:h4ck3rm1k3/aws-formula.git; popd
pushd matthew-parlette_cinnamon-formula; git remote add mdupont git@github.com:h4ck3rm1k3/cinnamon-formula.git; popd
pushd matthew-parlette_guake-formula; git remote add mdupont git@github.com:h4ck3rm1k3/guake-formula.git; popd
pushd matthew-parlette_openstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/openstack-formula.git; popd
pushd max-arnold_saltstack-postfix-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-postfix-formula.git; popd
pushd mcsrainbow_salt-states-hadoop; git remote add mdupont git@github.com:h4ck3rm1k3/salt-states-hadoop.git; popd
pushd mcsrainbow_salt-states-moosefs; git remote add mdupont git@github.com:h4ck3rm1k3/salt-states-moosefs.git; popd
pushd mgwilliams_jinja-test-formula; git remote add mdupont git@github.com:h4ck3rm1k3/jinja-test-formula.git; popd
pushd miguelpalma_saltstack-monit-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-monit-formula.git; popd
pushd ministryofjustice_cookiecutter-salt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/cookiecutter-salt-formula.git; popd
pushd ministryofjustice_elasticsearch-formula; git remote add mdupont git@github.com:h4ck3rm1k3/elasticsearch-formula.git; popd
pushd ministryofjustice_graphite-formula; git remote add mdupont git@github.com:h4ck3rm1k3/graphite-formula.git; popd
pushd ministryofjustice_mongodb-formula; git remote add mdupont git@github.com:h4ck3rm1k3/mongodb-formula.git; popd
pushd ministryofjustice_salt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula.git; popd
pushd ministryofjustice_salt-shaker; git remote add mdupont git@github.com:h4ck3rm1k3/salt-shaker.git; popd
pushd ministryofjustice_sentry-formula; git remote add mdupont git@github.com:h4ck3rm1k3/sentry-formula.git; popd
pushd ministryofjustice_utils-formula; git remote add mdupont git@github.com:h4ck3rm1k3/utils-formula.git; popd
pushd moniker-dns_elasticsearch-formula; git remote add mdupont git@github.com:h4ck3rm1k3/elasticsearch-formula.git; popd
pushd moreda_apache-saltstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/apache-saltstack-formula.git; popd
pushd moreda_mysql-saltstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/mysql-saltstack-formula.git; popd
pushd moreda_nginx-saltstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/nginx-saltstack-formula.git; popd
pushd moreda_php5-saltstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/php5-saltstack-formula.git; popd
pushd moreda_reposerver-saltstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/reposerver-saltstack-formula.git; popd
pushd moreda_saltstack-formulas-set; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-formulas-set.git; popd
pushd moreda_shorewall-saltstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/shorewall-saltstack-formula.git; popd
pushd moreda_sudo-saltstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/sudo-saltstack-formula.git; popd
pushd moreda_system-saltstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/system-saltstack-formula.git; popd
pushd moreda_users-saltstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/users-saltstack-formula.git; popd
pushd moreda_varnish-saltstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/varnish-saltstack-formula.git; popd
pushd moreda_zabbix-saltstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/zabbix-saltstack-formula.git; popd
pushd MrMarvin_mesosphere-formula; git remote add mdupont git@github.com:h4ck3rm1k3/mesosphere-formula.git; popd
pushd MSeven_btc-formula; git remote add mdupont git@github.com:h4ck3rm1k3/btc-formula.git; popd
pushd mutagendev_gitlab-ci-formula; git remote add mdupont git@github.com:h4ck3rm1k3/gitlab-ci-formula.git; popd
pushd nbari_my-salt; git remote add mdupont git@github.com:h4ck3rm1k3/my-salt.git; popd
pushd NeonXTX_gradle-formula; git remote add mdupont git@github.com:h4ck3rm1k3/gradle-formula.git; popd
pushd nmadhok_sumologic-formula; git remote add mdupont git@github.com:h4ck3rm1k3/sumologic-formula.git; popd
pushd nmadhok_zfs-formula; git remote add mdupont git@github.com:h4ck3rm1k3/zfs-formula.git; popd
pushd nvhbk16k53_saltstack-formulas; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-formulas.git; popd
pushd NVSeismoLab_antelope-formula; git remote add mdupont git@github.com:h4ck3rm1k3/antelope-formula.git; popd
pushd NVSeismoLab_obspy-formula; git remote add mdupont git@github.com:h4ck3rm1k3/obspy-formula.git; popd
pushd NVSeismoLab_ringserver-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ringserver-formula.git; popd
pushd oc_gitrepo-salt-state; git remote add mdupont git@github.com:h4ck3rm1k3/gitrepo-salt-state.git; popd
pushd oc_jvm-salt-state; git remote add mdupont git@github.com:h4ck3rm1k3/jvm-salt-state.git; popd
pushd oc_roninku; git remote add mdupont git@github.com:h4ck3rm1k3/roninku.git; popd
pushd openscihub_osh-salt-java; git remote add mdupont git@github.com:h4ck3rm1k3/osh-salt-java.git; popd
pushd p404_Salt-Formulas; git remote add mdupont git@github.com:h4ck3rm1k3/Salt-Formulas.git; popd
pushd pabluk_scrapy-formula; git remote add mdupont git@github.com:h4ck3rm1k3/scrapy-formula.git; popd
pushd pasipa2_saltstack-formulas; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-formulas.git; popd
pushd paystee_saltstack-sandbox; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-sandbox.git; popd
pushd paystee_users-formula; git remote add mdupont git@github.com:h4ck3rm1k3/users-formula.git; popd
pushd pengyao_salt-lvs; git remote add mdupont git@github.com:h4ck3rm1k3/salt-lvs.git; popd
pushd pengyao_salt-mysql; git remote add mdupont git@github.com:h4ck3rm1k3/salt-mysql.git; popd
pushd pengyao_salt-prereq-demo; git remote add mdupont git@github.com:h4ck3rm1k3/salt-prereq-demo.git; popd
pushd pengyao_salt-zabbix; git remote add mdupont git@github.com:h4ck3rm1k3/salt-zabbix.git; popd
pushd Pexeso_circus-formula; git remote add mdupont git@github.com:h4ck3rm1k3/circus-formula.git; popd
pushd Pexeso_pypack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/pypack-formula.git; popd
pushd philipsd6_twemproxy-formula-original; git remote add mdupont git@github.com:h4ck3rm1k3/twemproxy-formula-original.git; popd
pushd powellchristoph_sensu-formula; git remote add mdupont git@github.com:h4ck3rm1k3/sensu-formula.git; popd
pushd Psycojoker_cellar; git remote add mdupont git@github.com:h4ck3rm1k3/cellar.git; popd
pushd Psycojoker_dishes; git remote add mdupont git@github.com:h4ck3rm1k3/dishes.git; popd
pushd Psycojoker_ii-bot-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ii-bot-formula.git; popd
pushd Psycojoker_salt-test; git remote add mdupont git@github.com:h4ck3rm1k3/salt-test.git; popd
pushd publysher_infra-example-nginx; git remote add mdupont git@github.com:h4ck3rm1k3/infra-example-nginx.git; popd
pushd pyinx_saltstack-openstack-havana-rdo; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-openstack-havana-rdo.git; popd
pushd raadad_node-dev-vagrant-example; git remote add mdupont git@github.com:h4ck3rm1k3/node-dev-vagrant-example.git; popd
pushd rackeric_salt-hadoop; git remote add mdupont git@github.com:h4ck3rm1k3/salt-hadoop.git; popd
pushd rackeric_salt-nummr; git remote add mdupont git@github.com:h4ck3rm1k3/salt-nummr.git; popd
pushd rbolante_salt-mariadb; git remote add mdupont git@github.com:h4ck3rm1k3/salt-mariadb.git; popd
pushd reclass_test-sandbox; git remote add mdupont git@github.com:h4ck3rm1k3/test-sandbox.git; popd
pushd reinsle_apache-formula; git remote add mdupont git@github.com:h4ck3rm1k3/apache-formula.git; popd
pushd reinsle_debian-formula; git remote add mdupont git@github.com:h4ck3rm1k3/debian-formula.git; popd
pushd reinsle_dovecot-formula; git remote add mdupont git@github.com:h4ck3rm1k3/dovecot-formula.git; popd
pushd reinsle_editor-formula; git remote add mdupont git@github.com:h4ck3rm1k3/editor-formula.git; popd
pushd reinsle_einsle-formula; git remote add mdupont git@github.com:h4ck3rm1k3/einsle-formula.git; popd
pushd reinsle_packages-formula; git remote add mdupont git@github.com:h4ck3rm1k3/packages-formula.git; popd
pushd reinsle_screen-formula; git remote add mdupont git@github.com:h4ck3rm1k3/screen-formula.git; popd
pushd reinsle_shorewall-formula; git remote add mdupont git@github.com:h4ck3rm1k3/shorewall-formula.git; popd
pushd renoirb_openssl-formula; git remote add mdupont git@github.com:h4ck3rm1k3/openssl-formula.git; popd
pushd rfairburn_salt-grains-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-grains-formula.git; popd
pushd rfairburn_salt-nagios-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-nagios-formula.git; popd
pushd rilindo_cacti-formula; git remote add mdupont git@github.com:h4ck3rm1k3/cacti-formula.git; popd
pushd rilindo_ddclient-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ddclient-formula.git; popd
pushd roblayton_vim-formula; git remote add mdupont git@github.com:h4ck3rm1k3/vim-formula.git; popd
pushd robotice_Salt-Boardie-Formula; git remote add mdupont git@github.com:h4ck3rm1k3/Salt-Boardie-Formula.git; popd
pushd robotice_Salt-Robotice-Formula; git remote add mdupont git@github.com:h4ck3rm1k3/Salt-Robotice-Formula.git; popd
pushd rossnz_salt-formulas; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formulas.git; popd
pushd ross-p_zmq-formula; git remote add mdupont git@github.com:h4ck3rm1k3/zmq-formula.git; popd
pushd rotschopf_samba-formula; git remote add mdupont git@github.com:h4ck3rm1k3/samba-formula.git; popd
pushd rotschopf_virtualbox-formula; git remote add mdupont git@github.com:h4ck3rm1k3/virtualbox-formula.git; popd
pushd ryancurrah_limits-formula; git remote add mdupont git@github.com:h4ck3rm1k3/limits-formula.git; popd
pushd RyanHartje_Salt-Formulas; git remote add mdupont git@github.com:h4ck3rm1k3/Salt-Formulas.git; popd
pushd RyanHartje_salt-ossec-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-ossec-formula.git; popd
pushd sagansystems_sagan-salt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/sagan-salt-formula.git; popd
pushd sagansystems_salt-masterless-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-masterless-formula.git; popd
pushd saltstack-formulas_accumulo-formula; git remote add mdupont git@github.com:h4ck3rm1k3/accumulo-formula.git; popd
pushd saltstack-formulas_apache-formula; git remote add mdupont git@github.com:h4ck3rm1k3/apache-formula.git; popd
pushd saltstack-formulas_apt-cacher-formula; git remote add mdupont git@github.com:h4ck3rm1k3/apt-cacher-formula.git; popd
pushd saltstack-formulas_apt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/apt-formula.git; popd
pushd saltstack-formulas_aptly-formula; git remote add mdupont git@github.com:h4ck3rm1k3/aptly-formula.git; popd
pushd saltstack-formulas_avahi-formula; git remote add mdupont git@github.com:h4ck3rm1k3/avahi-formula.git; popd
pushd saltstack-formulas_backuptocloud-formula; git remote add mdupont git@github.com:h4ck3rm1k3/backuptocloud-formula.git; popd
pushd saltstack-formulas_beaver-formula; git remote add mdupont git@github.com:h4ck3rm1k3/beaver-formula.git; popd
pushd saltstack-formulas_bind-formula; git remote add mdupont git@github.com:h4ck3rm1k3/bind-formula.git; popd
pushd saltstack-formulas_boundary-formula; git remote add mdupont git@github.com:h4ck3rm1k3/boundary-formula.git; popd
pushd saltstack-formulas_build-essential-formula; git remote add mdupont git@github.com:h4ck3rm1k3/build-essential-formula.git; popd
pushd saltstack-formulas_canvas-formula; git remote add mdupont git@github.com:h4ck3rm1k3/canvas-formula.git; popd
pushd saltstack-formulas_ceph-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ceph-formula.git; popd
pushd saltstack-formulas_chef-formula; git remote add mdupont git@github.com:h4ck3rm1k3/chef-formula.git; popd
pushd saltstack-formulas_cherrypy-formula; git remote add mdupont git@github.com:h4ck3rm1k3/cherrypy-formula.git; popd
pushd saltstack-formulas_cloudstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/cloudstack-formula.git; popd
pushd saltstack-formulas_collectd-formula; git remote add mdupont git@github.com:h4ck3rm1k3/collectd-formula.git; popd
pushd saltstack-formulas_dansguardian-formula; git remote add mdupont git@github.com:h4ck3rm1k3/dansguardian-formula.git; popd
pushd saltstack-formulas_ddclient-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ddclient-formula.git; popd
pushd saltstack-formulas_dhcpd-formula; git remote add mdupont git@github.com:h4ck3rm1k3/dhcpd-formula.git; popd
pushd saltstack-formulas_django-formula; git remote add mdupont git@github.com:h4ck3rm1k3/django-formula.git; popd
pushd saltstack-formulas_djbdns-formula; git remote add mdupont git@github.com:h4ck3rm1k3/djbdns-formula.git; popd
pushd saltstack-formulas_dnsmasq-formula; git remote add mdupont git@github.com:h4ck3rm1k3/dnsmasq-formula.git; popd
pushd saltstack-formulas_docker-formula; git remote add mdupont git@github.com:h4ck3rm1k3/docker-formula.git; popd
pushd saltstack-formulas_dovecot-formula; git remote add mdupont git@github.com:h4ck3rm1k3/dovecot-formula.git; popd
pushd saltstack-formulas_drupal-formula; git remote add mdupont git@github.com:h4ck3rm1k3/drupal-formula.git; popd
pushd saltstack-formulas_ec2-autoscale-reactor; git remote add mdupont git@github.com:h4ck3rm1k3/ec2-autoscale-reactor.git; popd
pushd saltstack-formulas_ejabberd-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ejabberd-formula.git; popd
pushd saltstack-formulas_emacs-formula; git remote add mdupont git@github.com:h4ck3rm1k3/emacs-formula.git; popd
pushd saltstack-formulas_epel-formula; git remote add mdupont git@github.com:h4ck3rm1k3/epel-formula.git; popd
pushd saltstack-formulas_eramba-formula; git remote add mdupont git@github.com:h4ck3rm1k3/eramba-formula.git; popd
pushd saltstack-formulas_eucalyptus-formula; git remote add mdupont git@github.com:h4ck3rm1k3/eucalyptus-formula.git; popd
pushd saltstack-formulas_fail2ban-formula; git remote add mdupont git@github.com:h4ck3rm1k3/fail2ban-formula.git; popd
pushd saltstack-formulas_git-annex-formula; git remote add mdupont git@github.com:h4ck3rm1k3/git-annex-formula.git; popd
pushd saltstack-formulas_git-formula; git remote add mdupont git@github.com:h4ck3rm1k3/git-formula.git; popd
pushd saltstack-formulas_gitlab-formula; git remote add mdupont git@github.com:h4ck3rm1k3/gitlab-formula.git; popd
pushd saltstack-formulas_graphite-formula; git remote add mdupont git@github.com:h4ck3rm1k3/graphite-formula.git; popd
pushd saltstack-formulas_hadoop-formula; git remote add mdupont git@github.com:h4ck3rm1k3/hadoop-formula.git; popd
pushd saltstack-formulas_halite-formula; git remote add mdupont git@github.com:h4ck3rm1k3/halite-formula.git; popd
pushd saltstack-formulas_haproxy-formula; git remote add mdupont git@github.com:h4ck3rm1k3/haproxy-formula.git; popd
pushd saltstack-formulas_hostsfile-formula; git remote add mdupont git@github.com:h4ck3rm1k3/hostsfile-formula.git; popd
pushd saltstack-formulas_hosts-formula; git remote add mdupont git@github.com:h4ck3rm1k3/hosts-formula.git; popd
pushd saltstack-formulas_icinga2-formula; git remote add mdupont git@github.com:h4ck3rm1k3/icinga2-formula.git; popd
pushd saltstack-formulas_iptables-formula; git remote add mdupont git@github.com:h4ck3rm1k3/iptables-formula.git; popd
pushd saltstack-formulas_java-formula; git remote add mdupont git@github.com:h4ck3rm1k3/java-formula.git; popd
pushd saltstack-formulas_jdbc-formula; git remote add mdupont git@github.com:h4ck3rm1k3/jdbc-formula.git; popd
pushd saltstack-formulas_jenkins-formula; git remote add mdupont git@github.com:h4ck3rm1k3/jenkins-formula.git; popd
pushd saltstack-formulas_jmxtrans-formula; git remote add mdupont git@github.com:h4ck3rm1k3/jmxtrans-formula.git; popd
pushd saltstack-formulas_keystone-formula; git remote add mdupont git@github.com:h4ck3rm1k3/keystone-formula.git; popd
pushd saltstack-formulas_latex-formula; git remote add mdupont git@github.com:h4ck3rm1k3/latex-formula.git; popd
pushd saltstack-formulas_libvirt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/libvirt-formula.git; popd
pushd saltstack-formulas_linux-dev-formula; git remote add mdupont git@github.com:h4ck3rm1k3/linux-dev-formula.git; popd
pushd saltstack-formulas_logrotate-formula; git remote add mdupont git@github.com:h4ck3rm1k3/logrotate-formula.git; popd
pushd saltstack-formulas_logstash-formula; git remote add mdupont git@github.com:h4ck3rm1k3/logstash-formula.git; popd
pushd saltstack-formulas_lua-formula; git remote add mdupont git@github.com:h4ck3rm1k3/lua-formula.git; popd
pushd saltstack-formulas_maven-formula; git remote add mdupont git@github.com:h4ck3rm1k3/maven-formula.git; popd
pushd saltstack-formulas_memcached-formula; git remote add mdupont git@github.com:h4ck3rm1k3/memcached-formula.git; popd
pushd saltstack-formulas_mercurial-formula; git remote add mdupont git@github.com:h4ck3rm1k3/mercurial-formula.git; popd
pushd saltstack-formulas_mongodb-formula; git remote add mdupont git@github.com:h4ck3rm1k3/mongodb-formula.git; popd
pushd saltstack-formulas_moosefs-formula; git remote add mdupont git@github.com:h4ck3rm1k3/moosefs-formula.git; popd
pushd saltstack-formulas_munin-formula; git remote add mdupont git@github.com:h4ck3rm1k3/munin-formula.git; popd
pushd saltstack-formulas_mysql-formula; git remote add mdupont git@github.com:h4ck3rm1k3/mysql-formula.git; popd
pushd saltstack-formulas_nagios-formula; git remote add mdupont git@github.com:h4ck3rm1k3/nagios-formula.git; popd
pushd saltstack-formulas_nano-formula; git remote add mdupont git@github.com:h4ck3rm1k3/nano-formula.git; popd
pushd saltstack-formulas_newrelic-formula; git remote add mdupont git@github.com:h4ck3rm1k3/newrelic-formula.git; popd
pushd saltstack-formulas_nexus-formula; git remote add mdupont git@github.com:h4ck3rm1k3/nexus-formula.git; popd
pushd saltstack-formulas_nfs-formula; git remote add mdupont git@github.com:h4ck3rm1k3/nfs-formula.git; popd
pushd saltstack-formulas_nginx-formula; git remote add mdupont git@github.com:h4ck3rm1k3/nginx-formula.git; popd
pushd saltstack-formulas_node-formula; git remote add mdupont git@github.com:h4ck3rm1k3/node-formula.git; popd
pushd saltstack-formulas_nscd-formula; git remote add mdupont git@github.com:h4ck3rm1k3/nscd-formula.git; popd
pushd saltstack-formulas_ntp-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ntp-formula.git; popd
pushd saltstack-formulas_openldap-formula; git remote add mdupont git@github.com:h4ck3rm1k3/openldap-formula.git; popd
pushd saltstack-formulas_openssh-formula; git remote add mdupont git@github.com:h4ck3rm1k3/openssh-formula.git; popd
pushd saltstack-formulas_openstack-standalone-formula; git remote add mdupont git@github.com:h4ck3rm1k3/openstack-standalone-formula.git; popd
pushd saltstack-formulas_openvpn-client-formula; git remote add mdupont git@github.com:h4ck3rm1k3/openvpn-client-formula.git; popd
pushd saltstack-formulas_owncloud-formula; git remote add mdupont git@github.com:h4ck3rm1k3/owncloud-formula.git; popd
pushd saltstack-formulas_pam-ldap-formula; git remote add mdupont git@github.com:h4ck3rm1k3/pam-ldap-formula.git; popd
pushd saltstack-formulas_perl-formula; git remote add mdupont git@github.com:h4ck3rm1k3/perl-formula.git; popd
pushd saltstack-formulas_php-formula; git remote add mdupont git@github.com:h4ck3rm1k3/php-formula.git; popd
pushd saltstack-formulas_pip-formula; git remote add mdupont git@github.com:h4ck3rm1k3/pip-formula.git; popd
pushd saltstack-formulas_piwik-formula; git remote add mdupont git@github.com:h4ck3rm1k3/piwik-formula.git; popd
pushd saltstack-formulas_plone-formula; git remote add mdupont git@github.com:h4ck3rm1k3/plone-formula.git; popd
pushd saltstack-formulas_polycom-formula; git remote add mdupont git@github.com:h4ck3rm1k3/polycom-formula.git; popd
pushd saltstack-formulas_postfix-formula; git remote add mdupont git@github.com:h4ck3rm1k3/postfix-formula.git; popd
pushd saltstack-formulas_postgres-formula; git remote add mdupont git@github.com:h4ck3rm1k3/postgres-formula.git; popd
pushd saltstack-formulas_powerdns-formula; git remote add mdupont git@github.com:h4ck3rm1k3/powerdns-formula.git; popd
pushd saltstack-formulas_proftpd-formula; git remote add mdupont git@github.com:h4ck3rm1k3/proftpd-formula.git; popd
pushd saltstack-formulas_puppet-formula; git remote add mdupont git@github.com:h4ck3rm1k3/puppet-formula.git; popd
pushd saltstack-formulas_python2-formula; git remote add mdupont git@github.com:h4ck3rm1k3/python2-formula.git; popd
pushd saltstack-formulas_qpid-formula; git remote add mdupont git@github.com:h4ck3rm1k3/qpid-formula.git; popd
pushd saltstack-formulas_rabbitmq-formula; git remote add mdupont git@github.com:h4ck3rm1k3/rabbitmq-formula.git; popd
pushd saltstack-formulas_readthedocs-formula; git remote add mdupont git@github.com:h4ck3rm1k3/readthedocs-formula.git; popd
pushd saltstack-formulas_redis-formula; git remote add mdupont git@github.com:h4ck3rm1k3/redis-formula.git; popd
pushd saltstack-formulas_remi-formula; git remote add mdupont git@github.com:h4ck3rm1k3/remi-formula.git; popd
pushd saltstack-formulas_resolver-formula; git remote add mdupont git@github.com:h4ck3rm1k3/resolver-formula.git; popd
pushd saltstack-formulas_reverse-grains-formula; git remote add mdupont git@github.com:h4ck3rm1k3/reverse-grains-formula.git; popd
pushd saltstack-formulas_reverse-users-formula; git remote add mdupont git@github.com:h4ck3rm1k3/reverse-users-formula.git; popd
pushd saltstack-formulas_riak-formula; git remote add mdupont git@github.com:h4ck3rm1k3/riak-formula.git; popd
pushd saltstack-formulas_riemann-formula; git remote add mdupont git@github.com:h4ck3rm1k3/riemann-formula.git; popd
pushd saltstack-formulas_ruby-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ruby-formula.git; popd
pushd saltstack-formulas_salt-cloud-reactor; git remote add mdupont git@github.com:h4ck3rm1k3/salt-cloud-reactor.git; popd
pushd saltstack-formulas_salt-docs-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-docs-formula.git; popd
pushd saltstack-formulas_salt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula.git; popd
pushd saltstack-formulas_salt-virt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-virt-formula.git; popd
pushd saltstack-formulas_samba-formula; git remote add mdupont git@github.com:h4ck3rm1k3/samba-formula.git; popd
pushd saltstack-formulas_screen-formula; git remote add mdupont git@github.com:h4ck3rm1k3/screen-formula.git; popd
pushd saltstack-formulas_snmp-formula; git remote add mdupont git@github.com:h4ck3rm1k3/snmp-formula.git; popd
pushd saltstack-formulas_sphinx-doc-formula; git remote add mdupont git@github.com:h4ck3rm1k3/sphinx-doc-formula.git; popd
pushd saltstack-formulas_squid-formula; git remote add mdupont git@github.com:h4ck3rm1k3/squid-formula.git; popd
pushd saltstack-formulas_ssh-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ssh-formula.git; popd
pushd saltstack-formulas_sudoers-formula; git remote add mdupont git@github.com:h4ck3rm1k3/sudoers-formula.git; popd
pushd saltstack-formulas_sumo-logic-formula; git remote add mdupont git@github.com:h4ck3rm1k3/sumo-logic-formula.git; popd
pushd saltstack-formulas_sun-java-formula; git remote add mdupont git@github.com:h4ck3rm1k3/sun-java-formula.git; popd
pushd saltstack-formulas_svn-formula; git remote add mdupont git@github.com:h4ck3rm1k3/svn-formula.git; popd
pushd saltstack-formulas_syslog-ng-formula; git remote add mdupont git@github.com:h4ck3rm1k3/syslog-ng-formula.git; popd
pushd saltstack-formulas_sysstat-formula; git remote add mdupont git@github.com:h4ck3rm1k3/sysstat-formula.git; popd
pushd saltstack-formulas_template-formula; git remote add mdupont git@github.com:h4ck3rm1k3/template-formula.git; popd
pushd saltstack-formulas_thrift-formula; git remote add mdupont git@github.com:h4ck3rm1k3/thrift-formula.git; popd
pushd saltstack-formulas_tinc-formula; git remote add mdupont git@github.com:h4ck3rm1k3/tinc-formula.git; popd
pushd saltstack-formulas_tmux-formula; git remote add mdupont git@github.com:h4ck3rm1k3/tmux-formula.git; popd
pushd saltstack-formulas_tomcat-formula; git remote add mdupont git@github.com:h4ck3rm1k3/tomcat-formula.git; popd
pushd saltstack-formulas_twemproxy-formula; git remote add mdupont git@github.com:h4ck3rm1k3/twemproxy-formula.git; popd
pushd saltstack-formulas_users-formula; git remote add mdupont git@github.com:h4ck3rm1k3/users-formula.git; popd
pushd saltstack-formulas_varnish-formula; git remote add mdupont git@github.com:h4ck3rm1k3/varnish-formula.git; popd
pushd saltstack-formulas_vim-formula; git remote add mdupont git@github.com:h4ck3rm1k3/vim-formula.git; popd
pushd saltstack-formulas_virtualenv-formula; git remote add mdupont git@github.com:h4ck3rm1k3/virtualenv-formula.git; popd
pushd saltstack-formulas_vmware-tools-formula; git remote add mdupont git@github.com:h4ck3rm1k3/vmware-tools-formula.git; popd
pushd saltstack-formulas_wso2-formula; git remote add mdupont git@github.com:h4ck3rm1k3/wso2-formula.git; popd
pushd saltstack-formulas_zabbix-formula; git remote add mdupont git@github.com:h4ck3rm1k3/zabbix-formula.git; popd
pushd saltstack-formulas_zendserver-formula; git remote add mdupont git@github.com:h4ck3rm1k3/zendserver-formula.git; popd
pushd saltstack-formulas_zookeeper-formula; git remote add mdupont git@github.com:h4ck3rm1k3/zookeeper-formula.git; popd
pushd saltstackme_salt-rocks; git remote add mdupont git@github.com:h4ck3rm1k3/salt-rocks.git; popd
pushd saltstack_salt-contrib; git remote add mdupont git@github.com:h4ck3rm1k3/salt-contrib.git; popd
pushd saltstack_salt-states; git remote add mdupont git@github.com:h4ck3rm1k3/salt-states.git; popd
pushd saltstack_salt-vim; git remote add mdupont git@github.com:h4ck3rm1k3/salt-vim.git; popd
pushd saltstack_salt-vsx; git remote add mdupont git@github.com:h4ck3rm1k3/salt-vsx.git; popd
pushd saltstack_salty-vagrant; git remote add mdupont git@github.com:h4ck3rm1k3/salty-vagrant.git; popd
pushd sebw_salt-states; git remote add mdupont git@github.com:h4ck3rm1k3/salt-states.git; popd
pushd SEJeff_salt-states; git remote add mdupont git@github.com:h4ck3rm1k3/salt-states.git; popd
pushd semarie_openntpd-formula; git remote add mdupont git@github.com:h4ck3rm1k3/openntpd-formula.git; popd
pushd shano_salt-nzbget; git remote add mdupont git@github.com:h4ck3rm1k3/salt-nzbget.git; popd
pushd shano_salty-mailer; git remote add mdupont git@github.com:h4ck3rm1k3/salty-mailer.git; popd
pushd shano_salty-miner; git remote add mdupont git@github.com:h4ck3rm1k3/salty-miner.git; popd
pushd simpoir_salt-formula-shinken; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula-shinken.git; popd
pushd simpoir_salt-formula-teampass; git remote add mdupont git@github.com:h4ck3rm1k3/salt-formula-teampass.git; popd
pushd sivir_tinyproxy-formula; git remote add mdupont git@github.com:h4ck3rm1k3/tinyproxy-formula.git; popd
pushd SKoschnicke_basic-server-formula; git remote add mdupont git@github.com:h4ck3rm1k3/basic-server-formula.git; popd
pushd slafs_cookiecutter-saltstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/cookiecutter-saltstack-formula.git; popd
pushd slafs_example-formula; git remote add mdupont git@github.com:h4ck3rm1k3/example-formula.git; popd
pushd slafs_supervisor-formula; git remote add mdupont git@github.com:h4ck3rm1k3/supervisor-formula.git; popd
pushd smlloyd_saltstack-nsswitch-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-nsswitch-formula.git; popd
pushd smlloyd_saltstack-tzsetup-formula; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-tzsetup-formula.git; popd
pushd sphilippot_RDO-formula; git remote add mdupont git@github.com:h4ck3rm1k3/RDO-formula.git; popd
pushd spsoit_resourcespace-formula; git remote add mdupont git@github.com:h4ck3rm1k3/resourcespace-formula.git; popd
pushd sroegner_zookeeper-formula; git remote add mdupont git@github.com:h4ck3rm1k3/zookeeper-formula.git; popd
pushd stackdio-formulas_cdh4-formula; git remote add mdupont git@github.com:h4ck3rm1k3/cdh4-formula.git; popd
pushd stackforge_cinder-salt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/cinder-salt-formula.git; popd
pushd stackforge_glance-salt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/glance-salt-formula.git; popd
pushd stackforge_horizon-salt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/horizon-salt-formula.git; popd
pushd stackforge_keystone-salt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/keystone-salt-formula.git; popd
pushd stackforge_neutron-salt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/neutron-salt-formula.git; popd
pushd stackforge_nova-salt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/nova-salt-formula.git; popd
pushd stackforge_openstack-salt-formula; git remote add mdupont git@github.com:h4ck3rm1k3/openstack-salt-formula.git; popd
pushd StartledPhoenix_saltstack-mysql; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-mysql.git; popd
pushd StartledPhoenix_saltstack-syncthing; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-syncthing.git; popd
pushd stevage_salt-scripto; git remote add mdupont git@github.com:h4ck3rm1k3/salt-scripto.git; popd
pushd steveoliver_ceph-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ceph-formula.git; popd
pushd svetlyak40wt_salt-firewall-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-firewall-formula.git; popd
pushd syphernl_freepbx-formula; git remote add mdupont git@github.com:h4ck3rm1k3/freepbx-formula.git; popd
pushd taion809_oh-my-zsh-formula; git remote add mdupont git@github.com:h4ck3rm1k3/oh-my-zsh-formula.git; popd
pushd tateeskew_salt-states; git remote add mdupont git@github.com:h4ck3rm1k3/salt-states.git; popd
pushd tcpcloud_salt-opencontrail-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-opencontrail-formula.git; popd
pushd teepark_gitolite-formula; git remote add mdupont git@github.com:h4ck3rm1k3/gitolite-formula.git; popd
pushd tfolio_uwsgi-formula; git remote add mdupont git@github.com:h4ck3rm1k3/uwsgi-formula.git; popd
pushd theneykov_salt-fah; git remote add mdupont git@github.com:h4ck3rm1k3/salt-fah.git; popd
pushd ThomasKliszowski_gitlab-formula; git remote add mdupont git@github.com:h4ck3rm1k3/gitlab-formula.git; popd
pushd timc3_duplicity-formula; git remote add mdupont git@github.com:h4ck3rm1k3/duplicity-formula.git; popd
pushd timc3_salt-ssh-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-ssh-formula.git; popd
pushd timc3_tdagent-formula; git remote add mdupont git@github.com:h4ck3rm1k3/tdagent-formula.git; popd
pushd TimJones_openvpn-formula; git remote add mdupont git@github.com:h4ck3rm1k3/openvpn-formula.git; popd
pushd tinuva_firewalld-formula; git remote add mdupont git@github.com:h4ck3rm1k3/firewalld-formula.git; popd
pushd tinuva_salt-snmp; git remote add mdupont git@github.com:h4ck3rm1k3/salt-snmp.git; popd
pushd tinuva_selinux-formula; git remote add mdupont git@github.com:h4ck3rm1k3/selinux-formula.git; popd
pushd tinyclues_elasticsearch-kibana-formula; git remote add mdupont git@github.com:h4ck3rm1k3/elasticsearch-kibana-formula.git; popd
pushd tinyclues_oracle-java-formula; git remote add mdupont git@github.com:h4ck3rm1k3/oracle-java-formula.git; popd
pushd tobinquadros_vagrant-salt-tester; git remote add mdupont git@github.com:h4ck3rm1k3/vagrant-salt-tester.git; popd
pushd tony_salt-states-configs; git remote add mdupont git@github.com:h4ck3rm1k3/salt-states-configs.git; popd
pushd unknownlighter_formulas; git remote add mdupont git@github.com:h4ck3rm1k3/formulas.git; popd
pushd viktortnk_salt-cassandra-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-cassandra-formula.git; popd
pushd vinta_HeelsFetishism-Deployment; git remote add mdupont git@github.com:h4ck3rm1k3/HeelsFetishism-Deployment.git; popd
pushd viq_gitlab-formula; git remote add mdupont git@github.com:h4ck3rm1k3/gitlab-formula.git; popd
pushd virtru_common-formula; git remote add mdupont git@github.com:h4ck3rm1k3/common-formula.git; popd
pushd virtru_haproxy-formula; git remote add mdupont git@github.com:h4ck3rm1k3/haproxy-formula.git; popd
pushd virtru-ops_masterless; git remote add mdupont git@github.com:h4ck3rm1k3/masterless.git; popd
pushd virtru_packer-formula; git remote add mdupont git@github.com:h4ck3rm1k3/packer-formula.git; popd
pushd voltaire_spigot-fomula; git remote add mdupont git@github.com:h4ck3rm1k3/spigot-fomula.git; popd
pushd Vye_shinken-formula; git remote add mdupont git@github.com:h4ck3rm1k3/shinken-formula.git; popd
pushd Vye_yum-formula; git remote add mdupont git@github.com:h4ck3rm1k3/yum-formula.git; popd
pushd w3w_vnstat-formula; git remote add mdupont git@github.com:h4ck3rm1k3/vnstat-formula.git; popd
pushd wangqiang8511_cdh5-hadoop2-formula; git remote add mdupont git@github.com:h4ck3rm1k3/cdh5-hadoop2-formula.git; popd
pushd wangqiang8511_hive-formula; git remote add mdupont git@github.com:h4ck3rm1k3/hive-formula.git; popd
pushd wangqiang8511_mysql-formula; git remote add mdupont git@github.com:h4ck3rm1k3/mysql-formula.git; popd
pushd wangqiang8511_spark1-formula; git remote add mdupont git@github.com:h4ck3rm1k3/spark1-formula.git; popd
pushd wcannon_saltstack-related; git remote add mdupont git@github.com:h4ck3rm1k3/saltstack-related.git; popd
pushd webplatform_fxa-accounts-formula; git remote add mdupont git@github.com:h4ck3rm1k3/fxa-accounts-formula.git; popd
pushd westurner_apt-cacher-ng-formula; git remote add mdupont git@github.com:h4ck3rm1k3/apt-cacher-ng-formula.git; popd
pushd westurner_cookiecutter-saltformula; git remote add mdupont git@github.com:h4ck3rm1k3/cookiecutter-saltformula.git; popd
pushd westurner_dotfiles-formula; git remote add mdupont git@github.com:h4ck3rm1k3/dotfiles-formula.git; popd
pushd westurner_heka-formula; git remote add mdupont git@github.com:h4ck3rm1k3/heka-formula.git; popd
pushd westurner_htop-formula; git remote add mdupont git@github.com:h4ck3rm1k3/htop-formula.git; popd
pushd westurner_i3wm-formula; git remote add mdupont git@github.com:h4ck3rm1k3/i3wm-formula.git; popd
pushd westurner_ipython-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ipython-formula.git; popd
pushd westurner_mercurial-formula; git remote add mdupont git@github.com:h4ck3rm1k3/mercurial-formula.git; popd
pushd westurner_packer-formula; git remote add mdupont git@github.com:h4ck3rm1k3/packer-formula.git; popd
pushd westurner_python-formula; git remote add mdupont git@github.com:h4ck3rm1k3/python-formula.git; popd
pushd westurner_repos-formula; git remote add mdupont git@github.com:h4ck3rm1k3/repos-formula.git; popd
pushd westurner_shinken-formula; git remote add mdupont git@github.com:h4ck3rm1k3/shinken-formula.git; popd
pushd westurner_shorewall-formula; git remote add mdupont git@github.com:h4ck3rm1k3/shorewall-formula.git; popd
pushd westurner_supervisord-formula; git remote add mdupont git@github.com:h4ck3rm1k3/supervisord-formula.git; popd
pushd westurner_tortoisehg-formula; git remote add mdupont git@github.com:h4ck3rm1k3/tortoisehg-formula.git; popd
pushd westurner_ufw-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ufw-formula.git; popd
pushd westurner_vagrant-formula; git remote add mdupont git@github.com:h4ck3rm1k3/vagrant-formula.git; popd
pushd westurner_virtualbox-formula; git remote add mdupont git@github.com:h4ck3rm1k3/virtualbox-formula.git; popd
pushd westurner_wajig-formula; git remote add mdupont git@github.com:h4ck3rm1k3/wajig-formula.git; popd
pushd westurner_winswitch-formula; git remote add mdupont git@github.com:h4ck3rm1k3/winswitch-formula.git; popd
pushd whisklabs_salt-kafka-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-kafka-formula.git; popd
pushd whytewolf_elasticsearch-formula; git remote add mdupont git@github.com:h4ck3rm1k3/elasticsearch-formula.git; popd
pushd wikical_salt-duplicity; git remote add mdupont git@github.com:h4ck3rm1k3/salt-duplicity.git; popd
pushd xclusv_mailcatcher-formula; git remote add mdupont git@github.com:h4ck3rm1k3/mailcatcher-formula.git; popd
pushd xclusv_splunkforwarder-formula; git remote add mdupont git@github.com:h4ck3rm1k3/splunkforwarder-formula.git; popd
pushd yandex-sysmon_diamond-formula; git remote add mdupont git@github.com:h4ck3rm1k3/diamond-formula.git; popd
pushd yandex-sysmon_elasticlog-formula; git remote add mdupont git@github.com:h4ck3rm1k3/elasticlog-formula.git; popd
pushd yandex-sysmon_elasticsearch-formula; git remote add mdupont git@github.com:h4ck3rm1k3/elasticsearch-formula.git; popd
pushd yandex-sysmon_grafana-formula; git remote add mdupont git@github.com:h4ck3rm1k3/grafana-formula.git; popd
pushd yandex-sysmon_kibana-formula; git remote add mdupont git@github.com:h4ck3rm1k3/kibana-formula.git; popd
pushd yandex-sysmon_mini-dinstall-repo-formula; git remote add mdupont git@github.com:h4ck3rm1k3/mini-dinstall-repo-formula.git; popd
pushd yandex-sysmon_nginx-blocks-formula; git remote add mdupont git@github.com:h4ck3rm1k3/nginx-blocks-formula.git; popd
pushd yandex-sysmon_postfix-formula; git remote add mdupont git@github.com:h4ck3rm1k3/postfix-formula.git; popd
pushd yandex-sysmon_raava-formula; git remote add mdupont git@github.com:h4ck3rm1k3/raava-formula.git; popd
pushd yandex-sysmon_salt-minion-formula; git remote add mdupont git@github.com:h4ck3rm1k3/salt-minion-formula.git; popd
pushd yandex-sysmon_ssl-formula; git remote add mdupont git@github.com:h4ck3rm1k3/ssl-formula.git; popd
pushd yandex-sysmon_yasd-formula; git remote add mdupont git@github.com:h4ck3rm1k3/yasd-formula.git; popd
pushd yandex-sysmon_zookeeper-formula; git remote add mdupont git@github.com:h4ck3rm1k3/zookeeper-formula.git; popd
pushd yottatsa_openstack-formula; git remote add mdupont git@github.com:h4ck3rm1k3/openstack-formula.git; popd
pushd zhangcheng_salt-repo; git remote add mdupont git@github.com:h4ck3rm1k3/salt-repo.git; popd
