git submodule add https://github.com/0xf10e/radicale-formula.git 0xf10e_radicale-formula
git submodule add https://github.com/666jfox777/saltstack-elasticsearch-formula.git 666jfox777_saltstack-elasticsearch-formula
git submodule add https://github.com/666jfox777/saltstack-erlang-formula.git 666jfox777_saltstack-erlang-formula
git submodule add https://github.com/666jfox777/saltstack-grafana-formula.git 666jfox777_saltstack-grafana-formula
git submodule add https://github.com/666jfox777/saltstack-graphite-formula.git 666jfox777_saltstack-graphite-formula
git submodule add https://github.com/666jfox777/saltstack-kibana-formula.git 666jfox777_saltstack-kibana-formula
git submodule add https://github.com/666jfox777/saltstack-logstash-formula.git 666jfox777_saltstack-logstash-formula
git submodule add https://github.com/666jfox777/saltstack-rabbitmq-formula.git 666jfox777_saltstack-rabbitmq-formula
git submodule add https://github.com/666jfox777/saltstack-sensu-formula.git 666jfox777_saltstack-sensu-formula
git submodule add https://github.com/666jfox777/saltstack-statsite-formula.git 666jfox777_saltstack-statsite-formula
git submodule add https://github.com/666jfox777/saltstack-writr-formula.git 666jfox777_saltstack-writr-formula
git submodule add https://github.com/666jfox777/vagrant-monitor-everything.git 666jfox777_vagrant-monitor-everything
git submodule add https://github.com/7oku/open-vm-tools-formula.git 7oku_open-vm-tools-formula
git submodule add https://github.com/aboe76/docker_centos_salt.git aboe76_docker_centos_salt
git submodule add https://github.com/accumulo/mvn-formula.git accumulo_mvn-formula
git submodule add https://github.com/Adcade/buildbot-formula.git Adcade_buildbot-formula
git submodule add https://github.com/Adcade/logstash-formula.git Adcade_logstash-formula
git submodule add https://github.com/Adcade/oracle-java-formula.git Adcade_oracle-java-formula
git submodule add https://github.com/Adcade/pypicloud-formula.git Adcade_pypicloud-formula
git submodule add https://github.com/Adcade/redis-formula.git Adcade_redis-formula
git submodule add https://github.com/Adcade/snmp-formula.git Adcade_snmp-formula
git submodule add https://github.com/Adcade/statsd-formula.git Adcade_statsd-formula
git submodule add https://github.com/Adcade/thrift-formula.git Adcade_thrift-formula
git submodule add https://github.com/Adcade/vertx-formula.git Adcade_vertx-formula
git submodule add https://github.com/ahammond/salt_collectd.git ahammond_salt_collectd
git submodule add https://github.com/ahammond/salt_hosts.git ahammond_salt_hosts
git submodule add https://github.com/ahammond/salt_iptables.git ahammond_salt_iptables
git submodule add https://github.com/ahammond/salt_logstash.git ahammond_salt_logstash
git submodule add https://github.com/ahammond/salt_redis.git ahammond_salt_redis
git submodule add https://github.com/ahammond/salt_znc.git ahammond_salt_znc
git submodule add https://github.com/ahammond/salt_zookeeper.git ahammond_salt_zookeeper
git submodule add https://github.com/AislerHQ/couchdb-formula.git AislerHQ_couchdb-formula
git submodule add https://github.com/akoumjian/salt-django-example.git akoumjian_salt-django-example
git submodule add https://github.com/akoumjian/salt-git-module.git akoumjian_salt-git-module
git submodule add https://github.com/akoumjian/salty-vagrant.git akoumjian_salty-vagrant
git submodule add https://github.com/akoumjian/shaker.git akoumjian_shaker
git submodule add https://github.com/aletessier/salt-formulas.git aletessier_salt-formulas
git submodule add https://github.com/alexjennings/example-formula.git alexjennings_example-formula
git submodule add https://github.com/alexjennings/solr-formula.git alexjennings_solr-formula
git submodule add https://github.com/alexjennings/zookeeper-formula.git alexjennings_zookeeper-formula
git submodule add https://github.com/alex-leonhardt/sensu-formula.git alex-leonhardt_sensu-formula
git submodule add https://github.com/allanparsons/salt-supervisord.git allanparsons_salt-supervisord
git submodule add https://github.com/asmaps/bepasty-formula.git asmaps_bepasty-formula
git submodule add https://github.com/azuwis/gerrit-formula.git azuwis_gerrit-formula
git submodule add https://github.com/bclermont/states.git bclermont_states
git submodule add https://github.com/bechtoldt/amavis-formula.git bechtoldt_amavis-formula
git submodule add https://github.com/bechtoldt/aptcacherng-formula.git bechtoldt_aptcacherng-formula
git submodule add https://github.com/bechtoldt/apt-formula.git bechtoldt_apt-formula
git submodule add https://github.com/bechtoldt/bash-formula.git bechtoldt_bash-formula
git submodule add https://github.com/bechtoldt/binddns-formula.git bechtoldt_binddns-formula
git submodule add https://github.com/bechtoldt/clamav-formula.git bechtoldt_clamav-formula
git submodule add https://github.com/bechtoldt/crypto-formula.git bechtoldt_crypto-formula
git submodule add https://github.com/bechtoldt/dnsmasq-formula.git bechtoldt_dnsmasq-formula
git submodule add https://github.com/bechtoldt/dovecot-formula.git bechtoldt_dovecot-formula
git submodule add https://github.com/bechtoldt/ebtables-formula.git bechtoldt_ebtables-formula
git submodule add https://github.com/bechtoldt/ferm-formula.git bechtoldt_ferm-formula
git submodule add https://github.com/bechtoldt/file-formula.git bechtoldt_file-formula
git submodule add https://github.com/bechtoldt/foreman-formula.git bechtoldt_foreman-formula
git submodule add https://github.com/bechtoldt/git-formula.git bechtoldt_git-formula
git submodule add https://github.com/bechtoldt/gitlab-formula.git bechtoldt_gitlab-formula
git submodule add https://github.com/bechtoldt/grub-formula.git bechtoldt_grub-formula
git submodule add https://github.com/bechtoldt/httpd-formula.git bechtoldt_httpd-formula
git submodule add https://github.com/bechtoldt/ipa-formula.git bechtoldt_ipa-formula
git submodule add https://github.com/bechtoldt/iscdhcp-formula.git bechtoldt_iscdhcp-formula
git submodule add https://github.com/bechtoldt/java-formula.git bechtoldt_java-formula
git submodule add https://github.com/bechtoldt/keepalived-formula.git bechtoldt_keepalived-formula
git submodule add https://github.com/bechtoldt/libvirt-formula.git bechtoldt_libvirt-formula
git submodule add https://github.com/bechtoldt/linux-formula.git bechtoldt_linux-formula
git submodule add https://github.com/bechtoldt/liveconfig-formula.git bechtoldt_liveconfig-formula
git submodule add https://github.com/bechtoldt/mysql-formula.git bechtoldt_mysql-formula
git submodule add https://github.com/bechtoldt/network-formula.git bechtoldt_network-formula
git submodule add https://github.com/bechtoldt/nfs-formula.git bechtoldt_nfs-formula
git submodule add https://github.com/bechtoldt/nginx-formula.git bechtoldt_nginx-formula
git submodule add https://github.com/bechtoldt/omd-formula.git bechtoldt_omd-formula
git submodule add https://github.com/bechtoldt/opennebula-formula.git bechtoldt_opennebula-formula
git submodule add https://github.com/bechtoldt/openvswitch-formula.git bechtoldt_openvswitch-formula
git submodule add https://github.com/bechtoldt/php-formula.git bechtoldt_php-formula
git submodule add https://github.com/bechtoldt/postfix-formula.git bechtoldt_postfix-formula
git submodule add https://github.com/bechtoldt/postgresql-formula.git bechtoldt_postgresql-formula
git submodule add https://github.com/bechtoldt/redis-formula.git bechtoldt_redis-formula
git submodule add https://github.com/bechtoldt/repositorio-formula.git bechtoldt_repositorio-formula
git submodule add https://github.com/bechtoldt/rex-formula.git bechtoldt_rex-formula
git submodule add https://github.com/bechtoldt/salt-formula.git bechtoldt_salt-formula
git submodule add https://github.com/bechtoldt/saltstack-amavis-formula.git bechtoldt_saltstack-amavis-formula
git submodule add https://github.com/bechtoldt/saltstack-aptcacherng-formula.git bechtoldt_saltstack-aptcacherng-formula
git submodule add https://github.com/bechtoldt/saltstack-bash-formula.git bechtoldt_saltstack-bash-formula
git submodule add https://github.com/bechtoldt/saltstack-binddns-formula.git bechtoldt_saltstack-binddns-formula
git submodule add https://github.com/bechtoldt/saltstack-clamav-formula.git bechtoldt_saltstack-clamav-formula
git submodule add https://github.com/bechtoldt/saltstack-cron-formula.git bechtoldt_saltstack-cron-formula
git submodule add https://github.com/bechtoldt/saltstack-crypto-formula.git bechtoldt_saltstack-crypto-formula
git submodule add https://github.com/bechtoldt/saltstack-dnsmasq-formula.git bechtoldt_saltstack-dnsmasq-formula
git submodule add https://github.com/bechtoldt/saltstack-dovecot-formula.git bechtoldt_saltstack-dovecot-formula
git submodule add https://github.com/bechtoldt/saltstack-duply-formula.git bechtoldt_saltstack-duply-formula
git submodule add https://github.com/bechtoldt/saltstack-ebtables-formula.git bechtoldt_saltstack-ebtables-formula
git submodule add https://github.com/bechtoldt/saltstack-elasticsearch-formula.git bechtoldt_saltstack-elasticsearch-formula
git submodule add https://github.com/bechtoldt/saltstack-ferm-formula.git bechtoldt_saltstack-ferm-formula
git submodule add https://github.com/bechtoldt/saltstack-file-formula.git bechtoldt_saltstack-file-formula
git submodule add https://github.com/bechtoldt/saltstack-foreman-formula.git bechtoldt_saltstack-foreman-formula
git submodule add https://github.com/bechtoldt/saltstack-git-formula.git bechtoldt_saltstack-git-formula
git submodule add https://github.com/bechtoldt/saltstack-grub-formula.git bechtoldt_saltstack-grub-formula
git submodule add https://github.com/bechtoldt/saltstack-httpd-formula.git bechtoldt_saltstack-httpd-formula
git submodule add https://github.com/bechtoldt/saltstack-ipa-formula.git bechtoldt_saltstack-ipa-formula
git submodule add https://github.com/bechtoldt/saltstack-java-formula.git bechtoldt_saltstack-java-formula
git submodule add https://github.com/bechtoldt/saltstack-keepalived-formula.git bechtoldt_saltstack-keepalived-formula
git submodule add https://github.com/bechtoldt/saltstack-libvirt-formula.git bechtoldt_saltstack-libvirt-formula
git submodule add https://github.com/bechtoldt/saltstack-liveconfig-formula.git bechtoldt_saltstack-liveconfig-formula
git submodule add https://github.com/bechtoldt/saltstack-mongodb-formula.git bechtoldt_saltstack-mongodb-formula
git submodule add https://github.com/bechtoldt/saltstack-myback-formula.git bechtoldt_saltstack-myback-formula
git submodule add https://github.com/bechtoldt/saltstack-mysql-formula.git bechtoldt_saltstack-mysql-formula
git submodule add https://github.com/bechtoldt/saltstack-network-formula.git bechtoldt_saltstack-network-formula
git submodule add https://github.com/bechtoldt/saltstack-nfs-formula.git bechtoldt_saltstack-nfs-formula
git submodule add https://github.com/bechtoldt/saltstack-nginx-formula.git bechtoldt_saltstack-nginx-formula
git submodule add https://github.com/bechtoldt/saltstack-omd-formula.git bechtoldt_saltstack-omd-formula
git submodule add https://github.com/bechtoldt/saltstack-opennebula-formula.git bechtoldt_saltstack-opennebula-formula
git submodule add https://github.com/bechtoldt/saltstack-openvswitch-formula.git bechtoldt_saltstack-openvswitch-formula
git submodule add https://github.com/bechtoldt/saltstack-pam-formula.git bechtoldt_saltstack-pam-formula
git submodule add https://github.com/bechtoldt/saltstack-postfix-formula.git bechtoldt_saltstack-postfix-formula
git submodule add https://github.com/bechtoldt/saltstack-postgresql-formula.git bechtoldt_saltstack-postgresql-formula
git submodule add https://github.com/bechtoldt/saltstack-pulp-formula.git bechtoldt_saltstack-pulp-formula
git submodule add https://github.com/bechtoldt/saltstack-repositorio-formula.git bechtoldt_saltstack-repositorio-formula
git submodule add https://github.com/bechtoldt/saltstack-rex-formula.git bechtoldt_saltstack-rex-formula
git submodule add https://github.com/bechtoldt/saltstack-rssh-formula.git bechtoldt_saltstack-rssh-formula
git submodule add https://github.com/bechtoldt/saltstack-salt-formula.git bechtoldt_saltstack-salt-formula
git submodule add https://github.com/bechtoldt/saltstack-spamassassin-formula.git bechtoldt_saltstack-spamassassin-formula
git submodule add https://github.com/bechtoldt/saltstack-squid-formula.git bechtoldt_saltstack-squid-formula
git submodule add https://github.com/bechtoldt/saltstack-ssh-formula.git bechtoldt_saltstack-ssh-formula
git submodule add https://github.com/bechtoldt/saltstack-sudo-formula.git bechtoldt_saltstack-sudo-formula
git submodule add https://github.com/bechtoldt/saltstack-sysctl-formula.git bechtoldt_saltstack-sysctl-formula
git submodule add https://github.com/bechtoldt/saltstack-sysvinit-formula.git bechtoldt_saltstack-sysvinit-formula
git submodule add https://github.com/bechtoldt/saltstack-template-formula.git bechtoldt_saltstack-template-formula
git submodule add https://github.com/bechtoldt/saltstack-tftp-formula.git bechtoldt_saltstack-tftp-formula
git submodule add https://github.com/bechtoldt/saltstack-time-formula.git bechtoldt_saltstack-time-formula
git submodule add https://github.com/bechtoldt/saltstack-tinc-formula.git bechtoldt_saltstack-tinc-formula
git submodule add https://github.com/bechtoldt/saltstack-tools-formula.git bechtoldt_saltstack-tools-formula
git submodule add https://github.com/bechtoldt/saltstack-users-formula.git bechtoldt_saltstack-users-formula
git submodule add https://github.com/bechtoldt/saltstack-varnish-formula.git bechtoldt_saltstack-varnish-formula
git submodule add https://github.com/bechtoldt/saltstack-vim-formula.git bechtoldt_saltstack-vim-formula
git submodule add https://github.com/bechtoldt/saltstack-webapp-formula.git bechtoldt_saltstack-webapp-formula
git submodule add https://github.com/bechtoldt/saltstack-yubikey-formula.git bechtoldt_saltstack-yubikey-formula
git submodule add https://github.com/bechtoldt/saltstack-zsh-formula.git bechtoldt_saltstack-zsh-formula
git submodule add https://github.com/bechtoldt/spamassassin-formula.git bechtoldt_spamassassin-formula
git submodule add https://github.com/bechtoldt/squid-formula.git bechtoldt_squid-formula
git submodule add https://github.com/bechtoldt/ssh-formula.git bechtoldt_ssh-formula
git submodule add https://github.com/bechtoldt/ssl-formula.git bechtoldt_ssl-formula
git submodule add https://github.com/bechtoldt/sudo-formula.git bechtoldt_sudo-formula
git submodule add https://github.com/bechtoldt/sysctl-formula.git bechtoldt_sysctl-formula
git submodule add https://github.com/bechtoldt/template-formula.git bechtoldt_template-formula
git submodule add https://github.com/bechtoldt/tftp-formula.git bechtoldt_tftp-formula
git submodule add https://github.com/bechtoldt/time-formula.git bechtoldt_time-formula
git submodule add https://github.com/bechtoldt/tools-formula.git bechtoldt_tools-formula
git submodule add https://github.com/bechtoldt/users-formula.git bechtoldt_users-formula
git submodule add https://github.com/bechtoldt/vim-formula.git bechtoldt_vim-formula
git submodule add https://github.com/bechtoldt/zsh-formula.git bechtoldt_zsh-formula
git submodule add https://github.com/blarghmatey/aws-formula.git blarghmatey_aws-formula
git submodule add https://github.com/blarghmatey/elasticsearch-formula.git blarghmatey_elasticsearch-formula
git submodule add https://github.com/blarghmatey/kibana-formula.git blarghmatey_kibana-formula
git submodule add https://github.com/blarghmatey/logstash-formula.git blarghmatey_logstash-formula
git submodule add https://github.com/blarghmatey/mongo-mms-formula.git blarghmatey_mongo-mms-formula
git submodule add https://github.com/blarghmatey/nginx-formula.git blarghmatey_nginx-formula
git submodule add https://github.com/blarghmatey/salt-formulas.git blarghmatey_salt-formulas
git submodule add https://github.com/blarghmatey/saltstack-master.git blarghmatey_saltstack-master
git submodule add https://github.com/blarghmatey/uwsgi-formula.git blarghmatey_uwsgi-formula
git submodule add https://github.com/brandentimm/logstash-formula.git brandentimm_logstash-formula
git submodule add https://github.com/brandentimm/logstash_forwarder-formula.git brandentimm_logstash_forwarder-formula
git submodule add https://github.com/brandonhimpfen/ghost-formula.git brandonhimpfen_ghost-formula
git submodule add https://github.com/brandonhimpfen/wordpress-formula.git brandonhimpfen_wordpress-formula
git submodule add https://github.com/brutasse/states.git brutasse_states
git submodule add https://github.com/Cantemo/python27-saltstack-formula.git Cantemo_python27-saltstack-formula
git submodule add https://github.com/carlosperello/amavis-formula.git carlosperello_amavis-formula
git submodule add https://github.com/carlosperello/newrelic-formula.git carlosperello_newrelic-formula
git submodule add https://github.com/carlosperello/serverdensity-formula.git carlosperello_serverdensity-formula
git submodule add https://github.com/chekolyn/cherokee-formula.git chekolyn_cherokee-formula
git submodule add https://github.com/ckng/openjdk-formula.git ckng_openjdk-formula
git submodule add https://github.com/clemensberndt/jboss-fuse-formula.git clemensberndt_jboss-fuse-formula
git submodule add https://github.com/clemensberndt/rundeck-formula.git clemensberndt_rundeck-formula
git submodule add https://github.com/clemensberndt/servicemix-formula.git clemensberndt_servicemix-formula
git submodule add https://github.com/cmeisinger/salt-starters.git cmeisinger_salt-starters
git submodule add https://github.com/ctrlaltlinux/salt-formulas.git ctrlaltlinux_salt-formulas
git submodule add https://github.com/Cyclohex/formulas.git Cyclohex_formulas
git submodule add https://github.com/daemonna/saltstack-jenkins.git daemonna_saltstack-jenkins
git submodule add https://github.com/dani4571/drupal.git dani4571_drupal
git submodule add https://github.com/dani4571/magento.git dani4571_magento
git submodule add https://github.com/dani4571/mysql.git dani4571_mysql
git submodule add https://github.com/danieljn/salt-states.git danieljn_salt-states
git submodule add https://github.com/DataDog/datadog-formula.git DataDog_datadog-formula
git submodule add https://github.com/davidkarlsen/subsonic-formula.git davidkarlsen_subsonic-formula
git submodule add https://github.com/deuscapturus/saltstack-manageiq-formula.git deuscapturus_saltstack-manageiq-formula
git submodule add https://github.com/diegows/accumulo-formula.git diegows_accumulo-formula
git submodule add https://github.com/DigitalOcean-User-Projects/freepbx-saltstack-formula.git DigitalOcean-User-Projects_freepbx-saltstack-formula
git submodule add https://github.com/djl/motd-formula.git djl_motd-formula
git submodule add https://github.com/djl/timezone-formula.git djl_timezone-formula
git submodule add https://github.com/dlax/ckan-formula.git dlax_ckan-formula
git submodule add https://github.com/dmyerscough/salt-formulas.git dmyerscough_salt-formulas
git submodule add https://github.com/DockerNAS/nfs-yamlscript-formula.git DockerNAS_nfs-yamlscript-formula
git submodule add https://github.com/dockU/docker-formula.git dockU_docker-formula
git submodule add https://github.com/dstritzel/salt-experiments.git dstritzel_salt-experiments
git submodule add https://github.com/duk3luk3/nfs-user-formula.git duk3luk3_nfs-user-formula
git submodule add https://github.com/elastic-coders/saltstack-uwsgi-ng-formula.git elastic-coders_saltstack-uwsgi-ng-formula
git submodule add https://github.com/elextro/mariadb-galera-salt-ubuntu-formula.git elextro_mariadb-galera-salt-ubuntu-formula
git submodule add https://github.com/elvard/age-of-saltstack.git elvard_age-of-saltstack
git submodule add https://github.com/Enrise/apache-formula.git Enrise_apache-formula
git submodule add https://github.com/Enrise/composer-formula.git Enrise_composer-formula
git submodule add https://github.com/Enrise/mariadb-formula.git Enrise_mariadb-formula
git submodule add https://github.com/Enrise/nginx-formula.git Enrise_nginx-formula
git submodule add https://github.com/Enrise/node-formula.git Enrise_node-formula
git submodule add https://github.com/Enrise/phpfpm-formula.git Enrise_phpfpm-formula
git submodule add https://github.com/EntropyWorks/salt-openstack.git EntropyWorks_salt-openstack
git submodule add https://github.com/erzengel/node-formula.git erzengel_node-formula
git submodule add https://github.com/esacteksab/learning-salt.git esacteksab_learning-salt
git submodule add https://github.com/esacteksab/salt-states.git esacteksab_salt-states
git submodule add https://github.com/ExtremeSitting/hadoop-formula.git ExtremeSitting_hadoop-formula
git submodule add https://github.com/FEI-Lithicon/cobbler-formula.git FEI-Lithicon_cobbler-formula
git submodule add https://github.com/FEI-Lithicon/common-packages-formula.git FEI-Lithicon_common-packages-formula
git submodule add https://github.com/FEI-Lithicon/flexnet-server-formula.git FEI-Lithicon_flexnet-server-formula
git submodule add https://github.com/FEI-Lithicon/observium-formula.git FEI-Lithicon_observium-formula
git submodule add https://github.com/fessoga5/networkbsd-formula.git fessoga5_networkbsd-formula
git submodule add https://github.com/fessoga5/saltstack-cron-formula.git fessoga5_saltstack-cron-formula
git submodule add https://github.com/fintanmm/alfresco-formula.git fintanmm_alfresco-formula
git submodule add https://github.com/fintanmm/collectd-formula.git fintanmm_collectd-formula
git submodule add https://github.com/fintanmm/eramba-formula.git fintanmm_eramba-formula
git submodule add https://github.com/fintanmm/libreoffice-formula.git fintanmm_libreoffice-formula
git submodule add https://github.com/fintanmm/proftpd-formula.git fintanmm_proftpd-formula
git submodule add https://github.com/fintanmm/vmware-tools-formula.git fintanmm_vmware-tools-formula
git submodule add https://github.com/fly/rsyslogd-formula.git fly_rsyslogd-formula
git submodule add https://github.com/glomium/django-project-formula.git glomium_django-project-formula
git submodule add https://github.com/gravyboat/fail2ban-formula.git gravyboat_fail2ban-formula
git submodule add https://github.com/grengojbo/python3-formula.git grengojbo_python3-formula
git submodule add https://github.com/gspe/dropbox-formula.git gspe_dropbox-formula
git submodule add https://github.com/gsyt/salt-autofs.git gsyt_salt-autofs
git submodule add https://github.com/gsyt/salt-bind9.git gsyt_salt-bind9
git submodule add https://github.com/gsyt/salt-byobu.git gsyt_salt-byobu
git submodule add https://github.com/gsyt/salt-dhcpd.git gsyt_salt-dhcpd
git submodule add https://github.com/gsyt/salt-foreman.git gsyt_salt-foreman
git submodule add https://github.com/gsyt/salt-galera.git gsyt_salt-galera
git submodule add https://github.com/gsyt/salt-git.git gsyt_salt-git
git submodule add https://github.com/gsyt/salt-nfs.git gsyt_salt-nfs
git submodule add https://github.com/gsyt/salt-nrpe.git gsyt_salt-nrpe
git submodule add https://github.com/gsyt/salt-ntp.git gsyt_salt-ntp
git submodule add https://github.com/gsyt/salt-pkgs.git gsyt_salt-pkgs
git submodule add https://github.com/gsyt/salt-vim.git gsyt_salt-vim
git submodule add https://github.com/gsyt/salt-vmwaretools.git gsyt_salt-vmwaretools
git submodule add https://github.com/gsyt/salt-yum.git gsyt_salt-yum
git submodule add https://github.com/gsyt/salt-zsh.git gsyt_salt-zsh
git submodule add https://github.com/hipikat/chippery-formula.git hipikat_chippery-formula
git submodule add https://github.com/hipikat/git-server-formula.git hipikat_git-server-formula
git submodule add https://github.com/hipikat/homeboy-formula.git hipikat_homeboy-formula
git submodule add https://github.com/hipikat/salt-formulas.git hipikat_salt-formulas
git submodule add https://github.com/hipikat/saltlick-formula.git hipikat_saltlick-formula
git submodule add https://github.com/holmboe/django-saltapi.git holmboe_django-saltapi
git submodule add https://github.com/hotienvu/oracle-java7-salt-formula.git hotienvu_oracle-java7-salt-formula
git submodule add https://github.com/humankeyboard/salt-juno.git humankeyboard_salt-juno
git submodule add https://github.com/hvnsweeting/saltstates.git hvnsweeting_saltstates
git submodule add https://github.com/iamseth/elasticsearch-formula.git iamseth_elasticsearch-formula
git submodule add https://github.com/iamseth/rundeck-formula.git iamseth_rundeck-formula
git submodule add https://github.com/iamseth/sphinx-formula.git iamseth_sphinx-formula
git submodule add https://github.com/ibrahim1211/apccache-sls.git ibrahim1211_apccache-sls
git submodule add https://github.com/iluminite/reclass-tests.git iluminite_reclass-tests
git submodule add https://github.com/iluminite/salt-simple-stack.git iluminite_salt-simple-stack
git submodule add https://github.com/iluminite/vagrant-salt-example.git iluminite_vagrant-salt-example
git submodule add https://github.com/Inikup/subversion-formula.git Inikup_subversion-formula
git submodule add https://github.com/ipmb/hoodie-salt.git ipmb_hoodie-salt
git submodule add https://github.com/janusle/blog-env-formula.git janusle_blog-env-formula
git submodule add https://github.com/janusle/Yan-devbox-formula.git janusle_Yan-devbox-formula
git submodule add https://github.com/jarosser06/sysdig-formula.git jarosser06_sysdig-formula
git submodule add https://github.com/jaypei/saltstack-formulas-workenv.git jaypei_saltstack-formulas-workenv
git submodule add https://github.com/jeffh/Seafood.git jeffh_Seafood
git submodule add https://github.com/jeffrey4l/horizon-salt-formula.git jeffrey4l_horizon-salt-formula
git submodule add https://github.com/jesusaurus/salt-formula-apt.git jesusaurus_salt-formula-apt
git submodule add https://github.com/jesusaurus/salt-formula-datadog.git jesusaurus_salt-formula-datadog
git submodule add https://github.com/jesusaurus/salt-formula-elasticsearch.git jesusaurus_salt-formula-elasticsearch
git submodule add https://github.com/jesusaurus/salt-formula-fail2ban.git jesusaurus_salt-formula-fail2ban
git submodule add https://github.com/jesusaurus/salt-formula-haproxy.git jesusaurus_salt-formula-haproxy
git submodule add https://github.com/jesusaurus/salt-formula-logstash.git jesusaurus_salt-formula-logstash
git submodule add https://github.com/jesusaurus/salt-formula-nginx.git jesusaurus_salt-formula-nginx
git submodule add https://github.com/jesusaurus/salt-formula-ntp.git jesusaurus_salt-formula-ntp
git submodule add https://github.com/jesusaurus/salt-formula-openvpn.git jesusaurus_salt-formula-openvpn
git submodule add https://github.com/jesusaurus/salt-formula-percona.git jesusaurus_salt-formula-percona
git submodule add https://github.com/jesusaurus/salt-formula-rabbitmq.git jesusaurus_salt-formula-rabbitmq
git submodule add https://github.com/jesusaurus/salt-formula-redis.git jesusaurus_salt-formula-redis
git submodule add https://github.com/jesusaurus/salt-formula-tinc.git jesusaurus_salt-formula-tinc
git submodule add https://github.com/jesusaurus/salt-formula-upstart.git jesusaurus_salt-formula-upstart
git submodule add https://github.com/jianingy/saltstack-formula.git jianingy_saltstack-formula
git submodule add https://github.com/JoeHazzers/salt-formula.git JoeHazzers_salt-formula
git submodule add https://github.com/JoeHazzers/salt-formula-cern.git JoeHazzers_salt-formula-cern
git submodule add https://github.com/johnswanson/anaconda-formula.git johnswanson_anaconda-formula
git submodule add https://github.com/johnswanson/jds-formula.git johnswanson_jds-formula
git submodule add https://github.com/joshdover/albedolabs-salt-formulas.git joshdover_albedolabs-salt-formulas
git submodule add https://github.com/joshsmith2/salt-utils.git joshsmith2_salt-utils
git submodule add https://github.com/jxstanford/remi-formula.git jxstanford_remi-formula
git submodule add https://github.com/kennydo/salt-btsync-formula.git kennydo_salt-btsync-formula
git submodule add https://github.com/kennydo/salt-nginx-formula.git kennydo_salt-nginx-formula
git submodule add https://github.com/kennydo/salt-transmission-formula.git kennydo_salt-transmission-formula
git submodule add https://github.com/Kenshir0/apt-cacher-ng-formula.git Kenshir0_apt-cacher-ng-formula
git submodule add https://github.com/ketzacoatl/salt-aws-experiments.git ketzacoatl_salt-aws-experiments
git submodule add https://github.com/kevinschoon/supervisor-formula.git kevinschoon_supervisor-formula
git submodule add https://github.com/kindleit/nagios-formula.git kindleit_nagios-formula
git submodule add https://github.com/kjoconnor/salt-contrib.git kjoconnor_salt-contrib
git submodule add https://github.com/KrisSaxton/salt-ldap.git KrisSaxton_salt-ldap
git submodule add https://github.com/kshenk1/salt-formulas.git kshenk1_salt-formulas
git submodule add https://github.com/kvmate/kvmate-formula.git kvmate_kvmate-formula
git submodule add https://github.com/lblasc/ganeti-salt.git lblasc_ganeti-salt
git submodule add https://github.com/lemonlatte/mongodb-10gen.git lemonlatte_mongodb-10gen
git submodule add https://github.com/lemonlatte/openstack-formula.git lemonlatte_openstack-formula
git submodule add https://github.com/log0ymxm/salt-clojure.git log0ymxm_salt-clojure
git submodule add https://github.com/log0ymxm/salt-cuda.git log0ymxm_salt-cuda
git submodule add https://github.com/log0ymxm/salt-drake.git log0ymxm_salt-drake
git submodule add https://github.com/log0ymxm/salt-jvm.git log0ymxm_salt-jvm
git submodule add https://github.com/log0ymxm/salt-screen.git log0ymxm_salt-screen
git submodule add https://github.com/log0ymxm/salt-vowpal-wabbit.git log0ymxm_salt-vowpal-wabbit
git submodule add https://github.com/madflojo/salt-api-reactor-formula.git madflojo_salt-api-reactor-formula
git submodule add https://github.com/MadRussian/apt-cacher-formula.git MadRussian_apt-cacher-formula
git submodule add https://github.com/mafrosis/salt-formulae.git mafrosis_salt-formulae
git submodule add https://github.com/malept/gmusicprocurator-formula.git malept_gmusicprocurator-formula
git submodule add https://github.com/MarathonData/saltstack-formulas.git MarathonData_saltstack-formulas
git submodule add https://github.com/markcwill/mark-formulas.git markcwill_mark-formulas
git submodule add https://github.com/markkimsal/saltstack-formula-mariadb.git markkimsal_saltstack-formula-mariadb
git submodule add https://github.com/mathcamp/aws-formula.git mathcamp_aws-formula
git submodule add https://github.com/matthew-parlette/cinnamon-formula.git matthew-parlette_cinnamon-formula
git submodule add https://github.com/matthew-parlette/guake-formula.git matthew-parlette_guake-formula
git submodule add https://github.com/matthew-parlette/openstack-formula.git matthew-parlette_openstack-formula
git submodule add https://github.com/max-arnold/saltstack-postfix-formula.git max-arnold_saltstack-postfix-formula
git submodule add https://github.com/mcsrainbow/salt-states-hadoop.git mcsrainbow_salt-states-hadoop
git submodule add https://github.com/mcsrainbow/salt-states-moosefs.git mcsrainbow_salt-states-moosefs
git submodule add https://github.com/mgwilliams/jinja-test-formula.git mgwilliams_jinja-test-formula
git submodule add https://github.com/miguelpalma/saltstack-monit-formula.git miguelpalma_saltstack-monit-formula
git submodule add https://github.com/ministryofjustice/cookiecutter-salt-formula.git ministryofjustice_cookiecutter-salt-formula
git submodule add https://github.com/ministryofjustice/elasticsearch-formula.git ministryofjustice_elasticsearch-formula
git submodule add https://github.com/ministryofjustice/graphite-formula.git ministryofjustice_graphite-formula
git submodule add https://github.com/ministryofjustice/mongodb-formula.git ministryofjustice_mongodb-formula
git submodule add https://github.com/ministryofjustice/salt-formula.git ministryofjustice_salt-formula
git submodule add https://github.com/ministryofjustice/salt-shaker.git ministryofjustice_salt-shaker
git submodule add https://github.com/ministryofjustice/sentry-formula.git ministryofjustice_sentry-formula
git submodule add https://github.com/ministryofjustice/utils-formula.git ministryofjustice_utils-formula
git submodule add https://github.com/moniker-dns/elasticsearch-formula.git moniker-dns_elasticsearch-formula
git submodule add https://github.com/moreda/apache-saltstack-formula.git moreda_apache-saltstack-formula
git submodule add https://github.com/moreda/mysql-saltstack-formula.git moreda_mysql-saltstack-formula
git submodule add https://github.com/moreda/nginx-saltstack-formula.git moreda_nginx-saltstack-formula
git submodule add https://github.com/moreda/php5-saltstack-formula.git moreda_php5-saltstack-formula
git submodule add https://github.com/moreda/reposerver-saltstack-formula.git moreda_reposerver-saltstack-formula
git submodule add https://github.com/moreda/saltstack-formulas-set.git moreda_saltstack-formulas-set
git submodule add https://github.com/moreda/shorewall-saltstack-formula.git moreda_shorewall-saltstack-formula
git submodule add https://github.com/moreda/sudo-saltstack-formula.git moreda_sudo-saltstack-formula
git submodule add https://github.com/moreda/system-saltstack-formula.git moreda_system-saltstack-formula
git submodule add https://github.com/moreda/users-saltstack-formula.git moreda_users-saltstack-formula
git submodule add https://github.com/moreda/varnish-saltstack-formula.git moreda_varnish-saltstack-formula
git submodule add https://github.com/moreda/zabbix-saltstack-formula.git moreda_zabbix-saltstack-formula
git submodule add https://github.com/MrMarvin/mesosphere-formula.git MrMarvin_mesosphere-formula
git submodule add https://github.com/MSeven/btc-formula.git MSeven_btc-formula
git submodule add https://github.com/mutagendev/gitlab-ci-formula.git mutagendev_gitlab-ci-formula
git submodule add https://github.com/nbari/my-salt.git nbari_my-salt
git submodule add https://github.com/NeonXTX/gradle-formula.git NeonXTX_gradle-formula
git submodule add https://github.com/nmadhok/sumologic-formula.git nmadhok_sumologic-formula
git submodule add https://github.com/nmadhok/zfs-formula.git nmadhok_zfs-formula
git submodule add https://github.com/nvhbk16k53/saltstack-formulas.git nvhbk16k53_saltstack-formulas
git submodule add https://github.com/NVSeismoLab/antelope-formula.git NVSeismoLab_antelope-formula
git submodule add https://github.com/NVSeismoLab/obspy-formula.git NVSeismoLab_obspy-formula
git submodule add https://github.com/NVSeismoLab/ringserver-formula.git NVSeismoLab_ringserver-formula
git submodule add https://github.com/oc/gitrepo-salt-state.git oc_gitrepo-salt-state
git submodule add https://github.com/oc/jvm-salt-state.git oc_jvm-salt-state
git submodule add https://github.com/oc/roninku.git oc_roninku
git submodule add https://github.com/openscihub/osh-salt-java.git openscihub_osh-salt-java
git submodule add https://github.com/p404/Salt-Formulas.git p404_Salt-Formulas
git submodule add https://github.com/pabluk/scrapy-formula.git pabluk_scrapy-formula
git submodule add https://github.com/pasipa2/saltstack-formulas.git pasipa2_saltstack-formulas
git submodule add https://github.com/paystee/saltstack-sandbox.git paystee_saltstack-sandbox
git submodule add https://github.com/paystee/users-formula.git paystee_users-formula
git submodule add https://github.com/pengyao/salt-lvs.git pengyao_salt-lvs
git submodule add https://github.com/pengyao/salt-mysql.git pengyao_salt-mysql
git submodule add https://github.com/pengyao/salt-prereq-demo.git pengyao_salt-prereq-demo
git submodule add https://github.com/pengyao/salt-zabbix.git pengyao_salt-zabbix
git submodule add https://github.com/Pexeso/circus-formula.git Pexeso_circus-formula
git submodule add https://github.com/Pexeso/pypack-formula.git Pexeso_pypack-formula
git submodule add https://github.com/philipsd6/twemproxy-formula-original.git philipsd6_twemproxy-formula-original
git submodule add https://github.com/powellchristoph/sensu-formula.git powellchristoph_sensu-formula
git submodule add https://github.com/Psycojoker/cellar.git Psycojoker_cellar
git submodule add https://github.com/Psycojoker/dishes.git Psycojoker_dishes
git submodule add https://github.com/Psycojoker/ii-bot-formula.git Psycojoker_ii-bot-formula
git submodule add https://github.com/Psycojoker/salt-test.git Psycojoker_salt-test
git submodule add https://github.com/publysher/infra-example-nginx.git publysher_infra-example-nginx
git submodule add https://github.com/pyinx/saltstack-openstack-havana-rdo.git pyinx_saltstack-openstack-havana-rdo
git submodule add https://github.com/raadad/node-dev-vagrant-example.git raadad_node-dev-vagrant-example
git submodule add https://github.com/rackeric/salt-hadoop.git rackeric_salt-hadoop
git submodule add https://github.com/rackeric/salt-nummr.git rackeric_salt-nummr
git submodule add https://github.com/rbolante/salt-mariadb.git rbolante_salt-mariadb
git submodule add https://github.com/reclass/test-sandbox.git reclass_test-sandbox
git submodule add https://github.com/reinsle/apache-formula.git reinsle_apache-formula
git submodule add https://github.com/reinsle/debian-formula.git reinsle_debian-formula
git submodule add https://github.com/reinsle/dovecot-formula.git reinsle_dovecot-formula
git submodule add https://github.com/reinsle/editor-formula.git reinsle_editor-formula
git submodule add https://github.com/reinsle/einsle-formula.git reinsle_einsle-formula
git submodule add https://github.com/reinsle/packages-formula.git reinsle_packages-formula
git submodule add https://github.com/reinsle/screen-formula.git reinsle_screen-formula
git submodule add https://github.com/reinsle/shorewall-formula.git reinsle_shorewall-formula
git submodule add https://github.com/renoirb/openssl-formula.git renoirb_openssl-formula
git submodule add https://github.com/rfairburn/salt-grains-formula.git rfairburn_salt-grains-formula
git submodule add https://github.com/rfairburn/salt-nagios-formula.git rfairburn_salt-nagios-formula
git submodule add https://github.com/rilindo/cacti-formula.git rilindo_cacti-formula
git submodule add https://github.com/rilindo/ddclient-formula.git rilindo_ddclient-formula
git submodule add https://github.com/roblayton/vim-formula.git roblayton_vim-formula
git submodule add https://github.com/robotice/Salt-Boardie-Formula.git robotice_Salt-Boardie-Formula
git submodule add https://github.com/robotice/Salt-Robotice-Formula.git robotice_Salt-Robotice-Formula
git submodule add https://github.com/rossnz/salt-formulas.git rossnz_salt-formulas
git submodule add https://github.com/ross-p/zmq-formula.git ross-p_zmq-formula
git submodule add https://github.com/rotschopf/samba-formula.git rotschopf_samba-formula
git submodule add https://github.com/rotschopf/virtualbox-formula.git rotschopf_virtualbox-formula
git submodule add https://github.com/ryancurrah/limits-formula.git ryancurrah_limits-formula
git submodule add https://github.com/RyanHartje/Salt-Formulas.git RyanHartje_Salt-Formulas
git submodule add https://github.com/RyanHartje/salt-ossec-formula.git RyanHartje_salt-ossec-formula
git submodule add https://github.com/sagansystems/sagan-salt-formula.git sagansystems_sagan-salt-formula
git submodule add https://github.com/sagansystems/salt-masterless-formula.git sagansystems_salt-masterless-formula
git submodule add https://github.com/saltstack-formulas/accumulo-formula.git saltstack-formulas_accumulo-formula
git submodule add https://github.com/saltstack-formulas/apache-formula.git saltstack-formulas_apache-formula
git submodule add https://github.com/saltstack-formulas/apt-cacher-formula.git saltstack-formulas_apt-cacher-formula
git submodule add https://github.com/saltstack-formulas/apt-formula.git saltstack-formulas_apt-formula
git submodule add https://github.com/saltstack-formulas/aptly-formula.git saltstack-formulas_aptly-formula
git submodule add https://github.com/saltstack-formulas/avahi-formula.git saltstack-formulas_avahi-formula
git submodule add https://github.com/saltstack-formulas/backuptocloud-formula.git saltstack-formulas_backuptocloud-formula
git submodule add https://github.com/saltstack-formulas/beaver-formula.git saltstack-formulas_beaver-formula
git submodule add https://github.com/saltstack-formulas/bind-formula.git saltstack-formulas_bind-formula
git submodule add https://github.com/saltstack-formulas/boundary-formula.git saltstack-formulas_boundary-formula
git submodule add https://github.com/saltstack-formulas/build-essential-formula.git saltstack-formulas_build-essential-formula
git submodule add https://github.com/saltstack-formulas/canvas-formula.git saltstack-formulas_canvas-formula
git submodule add https://github.com/saltstack-formulas/ceph-formula.git saltstack-formulas_ceph-formula
git submodule add https://github.com/saltstack-formulas/chef-formula.git saltstack-formulas_chef-formula
git submodule add https://github.com/saltstack-formulas/cherrypy-formula.git saltstack-formulas_cherrypy-formula
git submodule add https://github.com/saltstack-formulas/cloudstack-formula.git saltstack-formulas_cloudstack-formula
git submodule add https://github.com/saltstack-formulas/collectd-formula.git saltstack-formulas_collectd-formula
git submodule add https://github.com/saltstack-formulas/dansguardian-formula.git saltstack-formulas_dansguardian-formula
git submodule add https://github.com/saltstack-formulas/ddclient-formula.git saltstack-formulas_ddclient-formula
git submodule add https://github.com/saltstack-formulas/dhcpd-formula.git saltstack-formulas_dhcpd-formula
git submodule add https://github.com/saltstack-formulas/django-formula.git saltstack-formulas_django-formula
git submodule add https://github.com/saltstack-formulas/djbdns-formula.git saltstack-formulas_djbdns-formula
git submodule add https://github.com/saltstack-formulas/dnsmasq-formula.git saltstack-formulas_dnsmasq-formula
git submodule add https://github.com/saltstack-formulas/docker-formula.git saltstack-formulas_docker-formula
git submodule add https://github.com/saltstack-formulas/dovecot-formula.git saltstack-formulas_dovecot-formula
git submodule add https://github.com/saltstack-formulas/drupal-formula.git saltstack-formulas_drupal-formula
git submodule add https://github.com/saltstack-formulas/ec2-autoscale-reactor.git saltstack-formulas_ec2-autoscale-reactor
git submodule add https://github.com/saltstack-formulas/ejabberd-formula.git saltstack-formulas_ejabberd-formula
git submodule add https://github.com/saltstack-formulas/emacs-formula.git saltstack-formulas_emacs-formula
git submodule add https://github.com/saltstack-formulas/epel-formula.git saltstack-formulas_epel-formula
git submodule add https://github.com/saltstack-formulas/eramba-formula.git saltstack-formulas_eramba-formula
git submodule add https://github.com/saltstack-formulas/eucalyptus-formula.git saltstack-formulas_eucalyptus-formula
git submodule add https://github.com/saltstack-formulas/fail2ban-formula.git saltstack-formulas_fail2ban-formula
git submodule add https://github.com/saltstack-formulas/git-annex-formula.git saltstack-formulas_git-annex-formula
git submodule add https://github.com/saltstack-formulas/git-formula.git saltstack-formulas_git-formula
git submodule add https://github.com/saltstack-formulas/gitlab-formula.git saltstack-formulas_gitlab-formula
git submodule add https://github.com/saltstack-formulas/graphite-formula.git saltstack-formulas_graphite-formula
git submodule add https://github.com/saltstack-formulas/hadoop-formula.git saltstack-formulas_hadoop-formula
git submodule add https://github.com/saltstack-formulas/halite-formula.git saltstack-formulas_halite-formula
git submodule add https://github.com/saltstack-formulas/haproxy-formula.git saltstack-formulas_haproxy-formula
git submodule add https://github.com/saltstack-formulas/hostsfile-formula.git saltstack-formulas_hostsfile-formula
git submodule add https://github.com/saltstack-formulas/hosts-formula.git saltstack-formulas_hosts-formula
git submodule add https://github.com/saltstack-formulas/icinga2-formula.git saltstack-formulas_icinga2-formula
git submodule add https://github.com/saltstack-formulas/iptables-formula.git saltstack-formulas_iptables-formula
git submodule add https://github.com/saltstack-formulas/java-formula.git saltstack-formulas_java-formula
git submodule add https://github.com/saltstack-formulas/jdbc-formula.git saltstack-formulas_jdbc-formula
git submodule add https://github.com/saltstack-formulas/jenkins-formula.git saltstack-formulas_jenkins-formula
git submodule add https://github.com/saltstack-formulas/jmxtrans-formula.git saltstack-formulas_jmxtrans-formula
git submodule add https://github.com/saltstack-formulas/keystone-formula.git saltstack-formulas_keystone-formula
git submodule add https://github.com/saltstack-formulas/latex-formula.git saltstack-formulas_latex-formula
git submodule add https://github.com/saltstack-formulas/libvirt-formula.git saltstack-formulas_libvirt-formula
git submodule add https://github.com/saltstack-formulas/linux-dev-formula.git saltstack-formulas_linux-dev-formula
git submodule add https://github.com/saltstack-formulas/logrotate-formula.git saltstack-formulas_logrotate-formula
git submodule add https://github.com/saltstack-formulas/logstash-formula.git saltstack-formulas_logstash-formula
git submodule add https://github.com/saltstack-formulas/lua-formula.git saltstack-formulas_lua-formula
git submodule add https://github.com/saltstack-formulas/maven-formula.git saltstack-formulas_maven-formula
git submodule add https://github.com/saltstack-formulas/memcached-formula.git saltstack-formulas_memcached-formula
git submodule add https://github.com/saltstack-formulas/mercurial-formula.git saltstack-formulas_mercurial-formula
git submodule add https://github.com/saltstack-formulas/mongodb-formula.git saltstack-formulas_mongodb-formula
git submodule add https://github.com/saltstack-formulas/moosefs-formula.git saltstack-formulas_moosefs-formula
git submodule add https://github.com/saltstack-formulas/munin-formula.git saltstack-formulas_munin-formula
git submodule add https://github.com/saltstack-formulas/mysql-formula.git saltstack-formulas_mysql-formula
git submodule add https://github.com/saltstack-formulas/nagios-formula.git saltstack-formulas_nagios-formula
git submodule add https://github.com/saltstack-formulas/nano-formula.git saltstack-formulas_nano-formula
git submodule add https://github.com/saltstack-formulas/newrelic-formula.git saltstack-formulas_newrelic-formula
git submodule add https://github.com/saltstack-formulas/nexus-formula.git saltstack-formulas_nexus-formula
git submodule add https://github.com/saltstack-formulas/nfs-formula.git saltstack-formulas_nfs-formula
git submodule add https://github.com/saltstack-formulas/nginx-formula.git saltstack-formulas_nginx-formula
git submodule add https://github.com/saltstack-formulas/node-formula.git saltstack-formulas_node-formula
git submodule add https://github.com/saltstack-formulas/nscd-formula.git saltstack-formulas_nscd-formula
git submodule add https://github.com/saltstack-formulas/ntp-formula.git saltstack-formulas_ntp-formula
git submodule add https://github.com/saltstack-formulas/openldap-formula.git saltstack-formulas_openldap-formula
git submodule add https://github.com/saltstack-formulas/openssh-formula.git saltstack-formulas_openssh-formula
git submodule add https://github.com/saltstack-formulas/openstack-standalone-formula.git saltstack-formulas_openstack-standalone-formula
git submodule add https://github.com/saltstack-formulas/openvpn-client-formula.git saltstack-formulas_openvpn-client-formula
git submodule add https://github.com/saltstack-formulas/owncloud-formula.git saltstack-formulas_owncloud-formula
git submodule add https://github.com/saltstack-formulas/pam-ldap-formula.git saltstack-formulas_pam-ldap-formula
git submodule add https://github.com/saltstack-formulas/perl-formula.git saltstack-formulas_perl-formula
git submodule add https://github.com/saltstack-formulas/php-formula.git saltstack-formulas_php-formula
git submodule add https://github.com/saltstack-formulas/pip-formula.git saltstack-formulas_pip-formula
git submodule add https://github.com/saltstack-formulas/piwik-formula.git saltstack-formulas_piwik-formula
git submodule add https://github.com/saltstack-formulas/plone-formula.git saltstack-formulas_plone-formula
git submodule add https://github.com/saltstack-formulas/polycom-formula.git saltstack-formulas_polycom-formula
git submodule add https://github.com/saltstack-formulas/postfix-formula.git saltstack-formulas_postfix-formula
git submodule add https://github.com/saltstack-formulas/postgres-formula.git saltstack-formulas_postgres-formula
git submodule add https://github.com/saltstack-formulas/powerdns-formula.git saltstack-formulas_powerdns-formula
git submodule add https://github.com/saltstack-formulas/proftpd-formula.git saltstack-formulas_proftpd-formula
git submodule add https://github.com/saltstack-formulas/puppet-formula.git saltstack-formulas_puppet-formula
git submodule add https://github.com/saltstack-formulas/python2-formula.git saltstack-formulas_python2-formula
git submodule add https://github.com/saltstack-formulas/qpid-formula.git saltstack-formulas_qpid-formula
git submodule add https://github.com/saltstack-formulas/rabbitmq-formula.git saltstack-formulas_rabbitmq-formula
git submodule add https://github.com/saltstack-formulas/readthedocs-formula.git saltstack-formulas_readthedocs-formula
git submodule add https://github.com/saltstack-formulas/redis-formula.git saltstack-formulas_redis-formula
git submodule add https://github.com/saltstack-formulas/remi-formula.git saltstack-formulas_remi-formula
git submodule add https://github.com/saltstack-formulas/resolver-formula.git saltstack-formulas_resolver-formula
git submodule add https://github.com/saltstack-formulas/reverse-grains-formula.git saltstack-formulas_reverse-grains-formula
git submodule add https://github.com/saltstack-formulas/reverse-users-formula.git saltstack-formulas_reverse-users-formula
git submodule add https://github.com/saltstack-formulas/riak-formula.git saltstack-formulas_riak-formula
git submodule add https://github.com/saltstack-formulas/riemann-formula.git saltstack-formulas_riemann-formula
git submodule add https://github.com/saltstack-formulas/ruby-formula.git saltstack-formulas_ruby-formula
git submodule add https://github.com/saltstack-formulas/salt-cloud-reactor.git saltstack-formulas_salt-cloud-reactor
git submodule add https://github.com/saltstack-formulas/salt-docs-formula.git saltstack-formulas_salt-docs-formula
git submodule add https://github.com/saltstack-formulas/salt-formula.git saltstack-formulas_salt-formula
git submodule add https://github.com/saltstack-formulas/salt-virt-formula.git saltstack-formulas_salt-virt-formula
git submodule add https://github.com/saltstack-formulas/samba-formula.git saltstack-formulas_samba-formula
git submodule add https://github.com/saltstack-formulas/screen-formula.git saltstack-formulas_screen-formula
git submodule add https://github.com/saltstack-formulas/snmp-formula.git saltstack-formulas_snmp-formula
git submodule add https://github.com/saltstack-formulas/sphinx-doc-formula.git saltstack-formulas_sphinx-doc-formula
git submodule add https://github.com/saltstack-formulas/squid-formula.git saltstack-formulas_squid-formula
git submodule add https://github.com/saltstack-formulas/ssh-formula.git saltstack-formulas_ssh-formula
git submodule add https://github.com/saltstack-formulas/sudoers-formula.git saltstack-formulas_sudoers-formula
git submodule add https://github.com/saltstack-formulas/sumo-logic-formula.git saltstack-formulas_sumo-logic-formula
git submodule add https://github.com/saltstack-formulas/sun-java-formula.git saltstack-formulas_sun-java-formula
git submodule add https://github.com/saltstack-formulas/svn-formula.git saltstack-formulas_svn-formula
git submodule add https://github.com/saltstack-formulas/syslog-ng-formula.git saltstack-formulas_syslog-ng-formula
git submodule add https://github.com/saltstack-formulas/sysstat-formula.git saltstack-formulas_sysstat-formula
git submodule add https://github.com/saltstack-formulas/template-formula.git saltstack-formulas_template-formula
git submodule add https://github.com/saltstack-formulas/thrift-formula.git saltstack-formulas_thrift-formula
git submodule add https://github.com/saltstack-formulas/tinc-formula.git saltstack-formulas_tinc-formula
git submodule add https://github.com/saltstack-formulas/tmux-formula.git saltstack-formulas_tmux-formula
git submodule add https://github.com/saltstack-formulas/tomcat-formula.git saltstack-formulas_tomcat-formula
git submodule add https://github.com/saltstack-formulas/twemproxy-formula.git saltstack-formulas_twemproxy-formula
git submodule add https://github.com/saltstack-formulas/users-formula.git saltstack-formulas_users-formula
git submodule add https://github.com/saltstack-formulas/varnish-formula.git saltstack-formulas_varnish-formula
git submodule add https://github.com/saltstack-formulas/vim-formula.git saltstack-formulas_vim-formula
git submodule add https://github.com/saltstack-formulas/virtualenv-formula.git saltstack-formulas_virtualenv-formula
git submodule add https://github.com/saltstack-formulas/vmware-tools-formula.git saltstack-formulas_vmware-tools-formula
git submodule add https://github.com/saltstack-formulas/wso2-formula.git saltstack-formulas_wso2-formula
git submodule add https://github.com/saltstack-formulas/zabbix-formula.git saltstack-formulas_zabbix-formula
git submodule add https://github.com/saltstack-formulas/zendserver-formula.git saltstack-formulas_zendserver-formula
git submodule add https://github.com/saltstack-formulas/zookeeper-formula.git saltstack-formulas_zookeeper-formula
git submodule add https://github.com/saltstackme/salt-rocks.git saltstackme_salt-rocks
git submodule add https://github.com/saltstack/salt-contrib.git saltstack_salt-contrib
git submodule add https://github.com/saltstack/salt-states.git saltstack_salt-states
git submodule add https://github.com/saltstack/salt-vim.git saltstack_salt-vim
git submodule add https://github.com/saltstack/salt-vsx.git saltstack_salt-vsx
git submodule add https://github.com/saltstack/salty-vagrant.git saltstack_salty-vagrant
git submodule add https://github.com/sebw/salt-states.git sebw_salt-states
git submodule add https://github.com/SEJeff/salt-states.git SEJeff_salt-states
git submodule add https://github.com/semarie/openntpd-formula.git semarie_openntpd-formula
git submodule add https://github.com/shano/salt-nzbget.git shano_salt-nzbget
git submodule add https://github.com/shano/salty-mailer.git shano_salty-mailer
git submodule add https://github.com/shano/salty-miner.git shano_salty-miner
git submodule add https://github.com/simpoir/salt-formula-shinken.git simpoir_salt-formula-shinken
git submodule add https://github.com/simpoir/salt-formula-teampass.git simpoir_salt-formula-teampass
git submodule add https://github.com/sivir/tinyproxy-formula.git sivir_tinyproxy-formula
git submodule add https://github.com/SKoschnicke/basic-server-formula.git SKoschnicke_basic-server-formula
git submodule add https://github.com/slafs/cookiecutter-saltstack-formula.git slafs_cookiecutter-saltstack-formula
git submodule add https://github.com/slafs/example-formula.git slafs_example-formula
git submodule add https://github.com/slafs/supervisor-formula.git slafs_supervisor-formula
git submodule add https://github.com/smlloyd/saltstack-nsswitch-formula.git smlloyd_saltstack-nsswitch-formula
git submodule add https://github.com/smlloyd/saltstack-tzsetup-formula.git smlloyd_saltstack-tzsetup-formula
git submodule add https://github.com/sphilippot/RDO-formula.git sphilippot_RDO-formula
git submodule add https://github.com/spsoit/resourcespace-formula.git spsoit_resourcespace-formula
git submodule add https://github.com/sroegner/zookeeper-formula.git sroegner_zookeeper-formula
git submodule add https://github.com/stackdio-formulas/cdh4-formula.git stackdio-formulas_cdh4-formula
git submodule add https://github.com/stackforge/cinder-salt-formula.git stackforge_cinder-salt-formula
git submodule add https://github.com/stackforge/glance-salt-formula.git stackforge_glance-salt-formula
git submodule add https://github.com/stackforge/horizon-salt-formula.git stackforge_horizon-salt-formula
git submodule add https://github.com/stackforge/keystone-salt-formula.git stackforge_keystone-salt-formula
git submodule add https://github.com/stackforge/neutron-salt-formula.git stackforge_neutron-salt-formula
git submodule add https://github.com/stackforge/nova-salt-formula.git stackforge_nova-salt-formula
git submodule add https://github.com/stackforge/openstack-salt-formula.git stackforge_openstack-salt-formula
git submodule add https://github.com/StartledPhoenix/saltstack-mysql.git StartledPhoenix_saltstack-mysql
git submodule add https://github.com/StartledPhoenix/saltstack-syncthing.git StartledPhoenix_saltstack-syncthing
git submodule add https://github.com/stevage/salt-scripto.git stevage_salt-scripto
git submodule add https://github.com/steveoliver/ceph-formula.git steveoliver_ceph-formula
git submodule add https://github.com/svetlyak40wt/salt-firewall-formula.git svetlyak40wt_salt-firewall-formula
git submodule add https://github.com/syphernl/freepbx-formula.git syphernl_freepbx-formula
git submodule add https://github.com/taion809/oh-my-zsh-formula.git taion809_oh-my-zsh-formula
git submodule add https://github.com/tateeskew/salt-states.git tateeskew_salt-states
git submodule add https://github.com/tcpcloud/salt-opencontrail-formula.git tcpcloud_salt-opencontrail-formula
git submodule add https://github.com/teepark/gitolite-formula.git teepark_gitolite-formula
git submodule add https://github.com/tfolio/uwsgi-formula.git tfolio_uwsgi-formula
git submodule add https://github.com/theneykov/salt-fah.git theneykov_salt-fah
git submodule add https://github.com/ThomasKliszowski/gitlab-formula.git ThomasKliszowski_gitlab-formula
git submodule add https://github.com/timc3/duplicity-formula.git timc3_duplicity-formula
git submodule add https://github.com/timc3/salt-ssh-formula.git timc3_salt-ssh-formula
git submodule add https://github.com/timc3/tdagent-formula.git timc3_tdagent-formula
git submodule add https://github.com/TimJones/openvpn-formula.git TimJones_openvpn-formula
git submodule add https://github.com/tinuva/firewalld-formula.git tinuva_firewalld-formula
git submodule add https://github.com/tinuva/salt-snmp.git tinuva_salt-snmp
git submodule add https://github.com/tinuva/selinux-formula.git tinuva_selinux-formula
git submodule add https://github.com/tinyclues/elasticsearch-kibana-formula.git tinyclues_elasticsearch-kibana-formula
git submodule add https://github.com/tinyclues/oracle-java-formula.git tinyclues_oracle-java-formula
git submodule add https://github.com/tobinquadros/vagrant-salt-tester.git tobinquadros_vagrant-salt-tester
git submodule add https://github.com/tony/salt-states-configs.git tony_salt-states-configs
git submodule add https://github.com/unknownlighter/formulas.git unknownlighter_formulas
git submodule add https://github.com/viktortnk/salt-cassandra-formula.git viktortnk_salt-cassandra-formula
git submodule add https://github.com/vinta/HeelsFetishism-Deployment.git vinta_HeelsFetishism-Deployment
git submodule add https://github.com/viq/gitlab-formula.git viq_gitlab-formula
git submodule add https://github.com/virtru/common-formula.git virtru_common-formula
git submodule add https://github.com/virtru/haproxy-formula.git virtru_haproxy-formula
git submodule add https://github.com/virtru-ops/masterless.git virtru-ops_masterless
git submodule add https://github.com/virtru/packer-formula.git virtru_packer-formula
git submodule add https://github.com/voltaire/spigot-fomula.git voltaire_spigot-fomula
git submodule add https://github.com/Vye/shinken-formula.git Vye_shinken-formula
git submodule add https://github.com/Vye/yum-formula.git Vye_yum-formula
git submodule add https://github.com/w3w/vnstat-formula.git w3w_vnstat-formula
git submodule add https://github.com/wangqiang8511/cdh5-hadoop2-formula.git wangqiang8511_cdh5-hadoop2-formula
git submodule add https://github.com/wangqiang8511/hive-formula.git wangqiang8511_hive-formula
git submodule add https://github.com/wangqiang8511/mysql-formula.git wangqiang8511_mysql-formula
git submodule add https://github.com/wangqiang8511/spark1-formula.git wangqiang8511_spark1-formula
git submodule add https://github.com/wcannon/saltstack-related.git wcannon_saltstack-related
git submodule add https://github.com/webplatform/fxa-accounts-formula.git webplatform_fxa-accounts-formula
git submodule add https://github.com/westurner/apt-cacher-ng-formula.git westurner_apt-cacher-ng-formula
git submodule add https://github.com/westurner/cookiecutter-saltformula.git westurner_cookiecutter-saltformula
git submodule add https://github.com/westurner/dotfiles-formula.git westurner_dotfiles-formula
git submodule add https://github.com/westurner/heka-formula.git westurner_heka-formula
git submodule add https://github.com/westurner/htop-formula.git westurner_htop-formula
git submodule add https://github.com/westurner/i3wm-formula.git westurner_i3wm-formula
git submodule add https://github.com/westurner/ipython-formula.git westurner_ipython-formula
git submodule add https://github.com/westurner/mercurial-formula.git westurner_mercurial-formula
git submodule add https://github.com/westurner/packer-formula.git westurner_packer-formula
git submodule add https://github.com/westurner/python-formula.git westurner_python-formula
git submodule add https://github.com/westurner/repos-formula.git westurner_repos-formula
git submodule add https://github.com/westurner/shinken-formula.git westurner_shinken-formula
git submodule add https://github.com/westurner/shorewall-formula.git westurner_shorewall-formula
git submodule add https://github.com/westurner/supervisord-formula.git westurner_supervisord-formula
git submodule add https://github.com/westurner/tortoisehg-formula.git westurner_tortoisehg-formula
git submodule add https://github.com/westurner/ufw-formula.git westurner_ufw-formula
git submodule add https://github.com/westurner/vagrant-formula.git westurner_vagrant-formula
git submodule add https://github.com/westurner/virtualbox-formula.git westurner_virtualbox-formula
git submodule add https://github.com/westurner/wajig-formula.git westurner_wajig-formula
git submodule add https://github.com/westurner/winswitch-formula.git westurner_winswitch-formula
git submodule add https://github.com/whisklabs/salt-kafka-formula.git whisklabs_salt-kafka-formula
git submodule add https://github.com/whytewolf/elasticsearch-formula.git whytewolf_elasticsearch-formula
git submodule add https://github.com/wikical/salt-duplicity.git wikical_salt-duplicity
git submodule add https://github.com/xclusv/mailcatcher-formula.git xclusv_mailcatcher-formula
git submodule add https://github.com/xclusv/splunkforwarder-formula.git xclusv_splunkforwarder-formula
git submodule add https://github.com/yandex-sysmon/diamond-formula.git yandex-sysmon_diamond-formula
git submodule add https://github.com/yandex-sysmon/elasticlog-formula.git yandex-sysmon_elasticlog-formula
git submodule add https://github.com/yandex-sysmon/elasticsearch-formula.git yandex-sysmon_elasticsearch-formula
git submodule add https://github.com/yandex-sysmon/grafana-formula.git yandex-sysmon_grafana-formula
git submodule add https://github.com/yandex-sysmon/kibana-formula.git yandex-sysmon_kibana-formula
git submodule add https://github.com/yandex-sysmon/mini-dinstall-repo-formula.git yandex-sysmon_mini-dinstall-repo-formula
git submodule add https://github.com/yandex-sysmon/nginx-blocks-formula.git yandex-sysmon_nginx-blocks-formula
git submodule add https://github.com/yandex-sysmon/postfix-formula.git yandex-sysmon_postfix-formula
git submodule add https://github.com/yandex-sysmon/raava-formula.git yandex-sysmon_raava-formula
git submodule add https://github.com/yandex-sysmon/salt-minion-formula.git yandex-sysmon_salt-minion-formula
git submodule add https://github.com/yandex-sysmon/ssl-formula.git yandex-sysmon_ssl-formula
git submodule add https://github.com/yandex-sysmon/yasd-formula.git yandex-sysmon_yasd-formula
git submodule add https://github.com/yandex-sysmon/zookeeper-formula.git yandex-sysmon_zookeeper-formula
git submodule add https://github.com/yottatsa/openstack-formula.git yottatsa_openstack-formula
git submodule add https://github.com/zhangcheng/salt-repo.git zhangcheng_salt-repo
